name: helgobox
description: A collection of creative tools that turn your DAW into a musical instrument.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.16.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # For (de)serializing objects of the real-time API
  protobuf: ^3.1.0
  # For talking to REAPER remotely
  grpc: ^4.0.1
  # For switching between pages
  go_router: ^14.2.8
  # For JSON (de)serialization
  json_annotation: ^4.7.0
  # For having additional List methods such as tryElementAt
  list_ext: ^1.0.4
  # Global reactive state management. Not used for the different notifiers in the models!
  flutter_riverpod: ^2.1.1
  # For an alternative to the Flutter Listenables that work both with Riverpod and Flutter
  flutter_state_notifier: ^1.0.0
  # For having a convenient immutable API objects (mainly used by the code generated from Rust)
  freezed_annotation: ^2.2.0
  # For logging
  loggy: ^2.0.3
  # For context menus
  context_menus: ^2.0.0
  # For DelegatingFuture needed in gRPC snackbar interceptor [MAYBE OPTIONAL SOON]
  async: ^2.11.0
  # For verifying authenticity of the server
  cryptography: ^2.7.0
  # For verifying authenticity of the server
  cryptography_flutter: ^2.3.2
  # For expandable form sections
  expandable: ^5.0.1
  # For volume meters
  geekyants_flutter_gauges: 1.0.4
  # For logo and "Connecting to REAPER..." animation
  google_fonts: ^6.2.1
  # For showing the multiple big parts of the GUI as split views
  multi_split_view: ^3.5.0
  # For more customizable dropdown button, used in Picky
  dropdown_button2: ^2.3.9
  # For custom dropdown button, currently not used [OPTIONAL]
  flutter_portal: ^1.1.4
  # For formatting help texts
  flutter_markdown: ^0.7.3
  # For "Connecting to REAPER..." animation
  animated_text_kit: ^4.2.2
  # For the 2D-scrollable part of the matrix
  two_dimensional_scrollables: ^0.3.2
  # For building native popup and context menus (user preference)
  native_context_menu: ^0.2.2+5
  # For getting information about the screen (not the window!)
  screen_retriever: ^0.1.9
  # E.g. for making Window full screen
  window_manager: ^0.4.2
  # For rendering links in help panel Markdown
  url_launcher: ^6.1.14
  # For Protobuf in-process transport
  ffi: ^2.1.0
  # For parsing command line arguments such as "--instance-id"
  args: ^2.4.2
  # For dropping files to import
  desktop_drop: ^0.5.0
  # For picking files to import
  file_picker: ^8.1.2
  # For less nesting
  flutter_hooks: ^0.20.3
  # For less nesting
  hooks_riverpod: ^2.4.5
  # For knob and drag field widgets
  pointer_lock:
    git:
      url: https://github.com/helgoboss/pointer_lock.git
      ref: main
  # For checking the host API version against our requirements
  pub_semver: ^2.1.4
  # For extracting the version number from pubspec.yaml and showing it
  yaml: ^3.1.2
  # For some audio-related icons
  material_design_icons_flutter: ^7.0.7296
  # For some audio-related icons
  font_awesome_flutter: ^10.6.0
  # For cool Helgobox logo effect
  shimmer: ^3.0.0
  # For formatting sequence timestamps
  timeago: ^3.6.0
  # For using the Playtime logo
  flutter_svg: ^2.0.10+1
  # For ReaLearn Projection
  dotted_border: ^2.1.0
  # For ReaLearn Projection
  flutter_arc_text: ^0.6.0
  # For ReaLearn Projection
  vibration: ^2.0.0
  # For ReaLearn Projection
  uuid: ^4.3.3
  # For using the voting service
  http: ^1.2.1
  # For hex conversion
  convert: ^3.1.1
  # For taking screenshots for docs
  screenshot: ^3.0.0
  # For saving screenshots for docs
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.5.4
  freezed: ^2.5.2

dependency_overrides:
  json_annotation:
#    path: ../json_serializable.dart/json_annotation
    git:
      url: https://github.com/helgoboss/json_serializable.dart.git
      ref: feature/json-key-flatten
      path: json_annotation
  json_serializable:
#    path: ../json_serializable.dart/json_serializable
    git:
      url: https://github.com/helgoboss/json_serializable.dart.git
      ref: feature/json-key-flatten
      path: json_serializable
  # Added support for left mouse click (official package seems to be abandoned)
  native_context_menu:
#    path: ../native_context_menu
    git:
      url: https://github.com/helgoboss/native_context_menu.git
      ref: feature/helgoboss
#  pointer_lock:
#    path: ../pointer_lock
  # Issues with a certain change (at least on macOS)
  # https://github.com/caduandrade/multi_split_view/issues/62#issuecomment-2350972583
  multi_split_view:
    #    path: ../multi_split_view
    git:
      url: https://github.com/helgoboss/multi_split_view.git
      ref: helgoboss

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     # For reading information about the app itself (about screen).
     - pubspec.yaml
     # Embedded fonts (at the moment the ones from Google Fonts, which are correctly named)
     - assets/fonts/
     # Embedded images
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages