-- This script was generated by Script: VF - ITEM - Advanced items repositioning.lua
reaper.SetExtState("vf_reposition_items", "interval_sec_noGUI", 0.0, true)
reaper.SetExtState("vf_reposition_items", "interval_frame_noGUI", 1, true)
reaper.SetExtState("vf_reposition_items", "interval_beats_noGUI", 5, true)
reaper.SetExtState("vf_reposition_items", "interval_mode_noGUI", 0, true)
reaper.SetExtState("vf_reposition_items", "offset_state_noGUI", tostring(false), true)
reaper.SetExtState("vf_reposition_items", "offset_val_noGUI", 3.0, true)
reaper.SetExtState("vf_reposition_items", "toggle_val_noGUI", 1, true)
reaper.SetExtState("vf_reposition_items", "mode_val_noGUI", 0, true)
reaper.SetExtState("vf_reposition_items", "overlap_noGUI", tostring(false), true)
reaper.SetExtState("vf_reposition_items", "adjacent_noGUI", tostring(false), true)
reaper.SetExtState("vf_reposition_items", "autoxfade_noGUI", tostring(true), true)
reaper.SetExtState("vf_reposition_items_settings", "group_offset_option_noGUI", tostring(true), true)
local script_path = debug.getinfo(1,'S').source:match[[^@?(.*[\/])[^\/]-$]]
local path = script_path .. "VF - ITEM - Advanced items repositioning - last values without GUI.lua"
if reaper.file_exists(path) then
	dofile(script_path .. "VF - ITEM - Advanced items repositioning - last values without GUI.lua")
else
	reaper.ShowMessageBox("Failed to run Advanced items repositioning script without GUI, please re-install the script in ReaPack", "ERROR", 0)
end
