-- @description Language library for Reanspiration script.
-- @version 3.10.0 (Added Modulation Strings)
-- @author Hosi
-- @about
--   This file contains all the text strings for the Reanspiration UI.
--   To add a new language, copy the entire 'en' table, rename the key (e.g., to 'fr' for French),
--   and translate all the string values. Then, update the 'available_languages' table in the main script.

local languages = {}

-- English Language Table
languages['en'] = {
  -- Window & Tabs
  window_title = 'Reanspiration - by Hosi (orig. phaselab)',
  
  -- Arranger King Bridge
  ak_bridge_title = "Arranger King Bridge",
  ak_btn_scan = "Scan Guide Track",
  ak_scan_success = "Successfully synced with Arranger King!",
  ak_scan_error = "Error: Please select the Arranger King Guide Track (MIDI) first.",
  ak_scan_failed_no_markers = "Scan Failed: No text markers or structure notes found in MIDI.",
  
  tab_generation = "Generation",
  tab_performance = "Performance",
  tab_creative_tools = "Creative Tools",
  tab_drums = "Drums",
  tab_arranger = "Arranger",
  tab_settings = "Settings",
    
  -- Drum Sequencer
  tab_drum_seq = "Drum Sequencer",
  drum_seq_desc = "32-Step Drum Machine (16th notes = 2 Bars)",
  drum_seq_clear = "Clear Grid",
  drum_seq_apply = "Apply to MIDI Item",
  drum_seq_load_midi = "Load from MIDI Item",
  drum_seq_user_preset_label = "User Preset:",
  drum_seq_new_preset = "[+] New Preset...",
  drum_seq_load_btn = "Load",
  drum_seq_save_btn = "Save",
  drum_seq_delete_btn = "Delete",
  drum_seq_save_popup_title = "Save Drum Preset",
  drum_seq_save_popup_name_label = "Preset Name:",
  drum_seq_save_popup_cancel = "Cancel",
  drum_seq_factory_ptn_label = "Factory Ptn:",
  drum_seq_select_pattern = "-- Select Pattern --",
  drum_seq_hide_empty_rows = "Hide Empty Rows",
  drum_seq_browse_btn = "Browse",
  drum_seq_browse_title = "Drum Preset Browser",
  drum_seq_browse_search_hint = "Search presets...",
  drum_seq_browse_user = "Uncategorized",
  drum_seq_browse_user_section = "User Presets",
  drum_seq_browse_lib_section = "Built-in Library",
  drum_seq_browse_no_results = "No presets found.",
  drum_ctx_set_genre = "Set Genre",
  drum_ctx_rename = "Rename",
  drum_ctx_duplicate = "Duplicate",
  drum_ctx_load = "Load Pattern",
  drum_ctx_genre_hint = "-- Quick pick --",
  drum_cat_rename_title = "Rename Category:",
  drum_cat_rename_ok = "OK",
  drum_seq_preview_err = "Preview failed: Track not Record-Armed or Input is not MIDI.",
    
  -- Generation Tab
  root_note_label = "Root Note",
  tooltip_detect_scale = "Analyze the selected MIDI item to automatically set the Root Note and Scale Type.",
  scale_type_label = "Scale Type",
  progression_label = "Progression",
  num_chords_label = "Number of Chords",
  complexity_label = "Complexity",
  tooltip_complexity = "0: Triads\n1: 7ths\n2: 9ths\n3: 11ths\n4: 13ths\n5: Altered",
  sec_dom_checkbox = "Add Secondary Dominants",
  tooltip_sec_dom = "50% chance to insert a V7 of the next chord (if it's not the tonic).",
  bass_pattern_label = "Bass Pattern",
  tooltip_bass_pattern = "Selects the pattern for the generated bassline.",
  
  -- NEW: Bass Walking Label
  bass_walking_label = "Walking Bass (Algorithmic)",
  bass_pattern_label_creative = "Bass Pattern",
  bass_lock_to_kick_checkbox = "Lock to Kick Drum",
  bass_error_no_drum_track = "Error: No track named 'Drum' found.",
  bass_error_no_kicks_found_msg = "Error: No Kick (Note 36) found in Drum track range.",
  
  -- NEW: Modulation Section
  mod_enable_checkbox = "Enable Modulation (Key Change)",
  mod_target_root_label = "Target Root",
  mod_target_scale_label = "Target Scale",
  mod_point_label = "Modulate at Chord #",
  mod_use_pivot_checkbox = "Use Pivot Chord",
  tooltip_mod_use_pivot = "Tries to use a common chord between both keys at the transition point for a smooth change.",
  
  -- NEW: Progression Tooltip Keys
  tooltip_progression_random = "Generates a random progression based on the 'Number of Chords'.",
  tooltip_progression_degree = "Degree",
  tooltip_progression_duration = "Duration (fraction of measure)",
  tooltip_progression_bass_degree = "Bass (Slash Chord)",
  
  generate_button = "Generate Chords & Bass",
  add_note_button = "Add Note",
  delete_chords_button = "Delete Chords (Keep Bass/Melody)",
  tooltip_delete_chords = "Deletes chord notes, keeping the generated bassline and melody.",
  
  -- NEW: Chord Viewer Section
  chord_viewer_section_title = "Chord Viewer",
  chord_viewer_analyze_button = "Analyze and Show Chords",
  tooltip_chord_viewer_analyze = "Analyzes MIDI in the item to detect chords and scale.",
  chord_viewer_clear_button = "Clear",
  chord_viewer_info_text = "Analyzed Chords:",
  chord_viewer_scale_info_text = "Analyzed Scale:",
  chord_viewer_success = "Analyzed %d chords.",
  chord_viewer_error_no_chords = "No valid chords found in item.",
  chord_viewer_popup_title = "Analyzed Chords",
  chord_viewer_popup_scale_title = "Detected Scale: %s",
  chord_viewer_popup_close_button = "Close",
  chord_viewer_unknown_scale = "Unknown/Ambiguous",
  
  -- Performance Tab
  transpose_label = "Transpose",
  spread_label = "Spread",
  tooltip_spread = "Controls spacing between chord notes (0=Tight, 2=Open).",
  voicing_label = "Voicing",
  tooltip_voicing = "Applies advanced voicing techniques (requires 4+ notes).",
  humanize_section_title = "Humanize",
  humanize_timing_label = "Timing +/- (PPQ)",
  humanize_velocity_label = "Velocity +/-",
  
  -- NEW: Groove Template
  humanize_groove_label = "Groove Template",
  groove_none = "None (Random)",
  groove_8th_medium = "8th Swing",
  groove_16th_light = "16th Swing",
  humanize_swing_label = "Swing %", -- NEW
  humanize_accent_label = "Velocity Accent", -- NEW
  vel_accent_none = "None", -- NEW
  vel_accent_strong = "Strong (1 & 3)", -- NEW
  vel_accent_weak = "Weak (2 & 4)", -- NEW
  vel_accent_sync = "Syncopated", -- NEW
  
  humanize_button = "Humanize Notes",
  tooltip_humanize = "Slightly randomizes the timing and velocity of all notes in the item based on the selected groove.",
  undo_humanize_button = "Undo Humanize",

  -- Creative Tools Tab
  melody_section_title = "Melody Generation",
  melody_contour_label = "Contour",
  contour_random = "Random",
  contour_ascending = "Ascending",
  contour_arch = "Arch",
  contour_descending = "Descending",
  contour_valley = "Valley",
  contour_markov = "Markov Chain",
  contour_counterpoint = "Counterpoint (Contrary)",
  contour_thematic = "Thematic (Motif)",
  melody_structure_label = "Structure", -- NEW
  tooltip_melody_contour = "Sets the overall melodic shape.",
  
  -- NEW: Melody Pattern Library
  melody_pattern_label = "Melody Pattern",
  melody_pattern_none = "None (Tension/Release)",
  
  melody_density_label = "Density",
  melody_min_oct_label = "Min Octave",
  melody_max_oct_label = "Max Octave",
  melody_generate_button = "Generate Melody",
  tooltip_melody_generate = "Generates a new melody based on the selected Pattern, active Motif, or Tension/Release logic.",
  undo_melody_button = "Undo Melody",
  
  -- Motif Keys
  melody_generate_motif_button = "Generate Motif",
  tooltip_melody_generate_motif = "Generates a 1-bar melodic idea based on the first chord.\nThis Motif will be used if 'Melody Pattern' is set to 'None'.",
  melody_clear_motif_button = "Clear Motif",
  melody_motif_active_text = "Active Motif: %d notes",
  melody_motif_tooltip_text = "Motif Notes:\n%s", 
  melody_motif_cleared_text = "Motif cleared.",
  melody_motif_generated_text = "Motif generated (%d notes).",
  melody_motif_error_no_chords = "Cannot generate motif: No chords found in item or chord track.",
  
  melody_generate_counter_button = "Generate Counter-Melody",
  tooltip_melody_generate_counter = "Generates a second melody based on the main melody.\nDeletes any previous counter-melody.",
  undo_counter_melody_button = "Undo Counter-Melody",
  
  -- NEW: Adaptive Markov Keys
  melody_markov_learn_button = "Learn from Selection",
  tooltip_melody_markov_learn = "Analyzes the melody in the selected item and updates the Markov Chain probabilities to match its style.\nUse 'Markov Chain' in Contour.",
  melody_markov_status_default = "Markov: Default",
  melody_markov_status_learned = "Markov: Learned from User",
  melody_markov_error_no_notes = "Error: No melody notes found in the selected item to learn from.",
  
  -- NEW: Melody Mutator Section
  melody_mutator_section_title = "Melody Mutator",
  melody_mutate_invert_button = "Invert Pitch",
  tooltip_melody_mutate_invert = "Inverts the pitch intervals of the melody around the first note.",
  melody_mutate_retrograde_button = "Retrograde (Reverse)",
  tooltip_melody_mutate_retrograde = "Reverses the melody, playing it from end to start.",
  melody_mutate_displace_label = "Displacement (PPQ)",
  melody_mutate_displace_button = "Displace Rhythm",
  tooltip_melody_mutate_displace = "Shifts all melody notes forward or backward by the specified PPQ amount.",
  undo_melody_mutation_button = "Undo Mutation",

  -- NEW: Cinematic Ostinato Section
  ostinato_section_title = "Cinematic Ostinato",
  ostinato_len_label = "Pattern Length",
  ostinato_buildup_label = "Build-up (%)",
  btn_gen_ostinato = "Generate Ostinato",
  btn_undo_ostinato = "Undo Ostinato",

  bass_section_title = "Bass Generation",
  bass_pattern_label_creative = "Pattern##BassCreative",
  bass_generate_button = "Generate Bass",
  tooltip_bass_generate = "Generates a new bassline over existing chords.\nDeletes any previous bassline.",
  undo_bass_button = "Undo Bass",
  
  arp_strum_section_title = "Arpeggiator / Strummer",
  arp_strum_pattern_label = "Pattern##Arp", -- Obsolete, but kept for safety
  arp_strum_delay_label = "Strum Delay (PPQ)",
  arp_strum_velocity_label = "Up-strum Velocity (%)",
  tooltip_arp_strum_velocity = "Sets the velocity of up-strums as a percentage of the original note's velocity.",
  arp_rate_label = "Arp Rate",
  arp_apply_button = "Apply Arp/Strum",
  tooltip_arp_apply = "Applies pattern to selected notes (or all if none selected).",
  undo_arp_button = "Undo Arp/Strum",
  
  -- NEW KEYS FOR ARP/STRUM SPLIT
  mode_none = "None",
  mode_arp = "Arpeggiator",
  mode_strum = "Strummer",
  perform_mode_label = "Mode",
  arp_pattern_label = "Arp Pattern",
  strum_pattern_label = "Strum Pattern",
  tooltip_strum_pattern = "Select a strumming pattern from the library.",
  
  -- NEW: Arp Euclidean
  arp_euclidean_enable_checkbox = "Use Euclidean Rhythm",
  arp_euclidean_steps_label = "Euc Steps",
  arp_euclidean_hits_label = "Euc Hits",
  
  -- NEW: Guitar Strumming Keys
  strum_palm_mute_checkbox = "Palm Mute (Guitar)",
  strum_guitar_voicing_checkbox = "Guitar Voicing (Open Strings)",
  strum_up_stroke_sf_label = "Up-Stroke Latency Scale",
  
  rhythm_section_title = "Rhythm Applicator",
  rhythm_pattern_label = "Rhythm Pattern",
  rhythm_apply_button = "Apply Rhythm",
  tooltip_rhythm_apply = "Applies the selected rhythmic pattern to the chords.",
  undo_rhythm_button = "Undo Rhythm",

  -- Drums Tab
  drum_pattern_label = "Drum Pattern",
  drum_generate_button = "Generate Drums",
  tooltip_drum_generate = "Generates a drum beat for the entire item length.\nDeletes any previous drum notes.",
  drum_generate_fill_button = "Generate Fill",
  tooltip_drum_generate_fill = "Generates a drum fill in the last measure of the item.",
  drum_generate_variation_button = "Create Variation",
  tooltip_drum_generate_variation = "Randomly adds/removes a few Kick/Hi-Hat notes from the current drum pattern.",
  drum_error_no_chords = "Please generate chords or have some MIDI notes in the item first.",
  
  -- NEW: Euclidean Sequencer Section
  euclidean_section_title = "Euclidean Sequencer",
  euclidean_instrument_label = "Instrument",
  euclidean_steps_label = "Steps (16ths)",
  euclidean_hits_label = "Hits",
  euclidean_rotation_label = "Rotation",
  euclidean_generate_button = "Generate Layer",
  tooltip_euclidean_generate = "Generates a rhythmic layer for the selected instrument using Euclidean algorithm.\nReplaces existing notes for this instrument only.",

  -- Arranger Tab
  arranger_section_title = "Project Arranger",
  arranger_sync_button = "Sync from Project Regions",
  arranger_sync_tooltip = "Reads all Regions from the current Reaper project and populates the list below.",
  arranger_structure_title = "Song Structure (Regions)",
  arranger_col_id = "ID",
  arranger_col_name = "Name",
  arranger_col_energy = "Energy",
  arranger_col_pos = "Start",
  arranger_col_len = "Length",
  arranger_col_actions = "Actions",
  arranger_action_glue = "Glue",
  arranger_btn_glue_all = "Glue All Regions",
  arranger_state_glued = "✓ Glued",
  arranger_info_text = "Use Regions in REAPER to define your song sections (Verse, Chorus, etc.).",
  arranger_no_regions = "No regions found in project.",
  
  arranger_pool_title = "Pattern Pool",
  expression_section_title = "Dynamic Expression Engine",
  expression_dynamics_label = "Dynamics (%)",
  expression_follow_pitch_checkbox = "Follow Pitch (Swell)",
  expression_breath_checkbox = "Breath (Phrase End Dip)",
  expression_legato_label = "Legato Overlap (ms)",
  expression_smart_pedal_checkbox = "Smart Sustain Pedal",
  expression_apply_button = "Apply Expression",
  undo_expression_button = "Undo Expression",
  tooltip_expression_dynamics = "Controls the range of CC1/CC11 modulation.",
  tooltip_expression_breath = "Automatically dips expression at the end of phrases to simulate breathing.",
  arranger_save_button = "Save Item as Pattern",
  arranger_rename_button = "Rename",
  arranger_delete_button = "Delete",
  arranger_add_button = "Add",
  arranger_move_up_button = "Move Up",
  arranger_move_down_button = "Move Down",
  arranger_remove_button = "Remove",
  arranger_output_track_label = "Output Track Name",
  arranger_regions_checkbox = "Create Regions for Sections",
  arranger_generate_button = "GENERATE ARRANGEMENT",
  arranger_popup_savename_title = "Save New Pattern",
  arranger_popup_savename_prompt = "Enter a name for the new pattern:",
  arranger_popup_renamename_title = "Rename Pattern",
  arranger_popup_rename_prompt = "Enter the new name:",
  arranger_popup_delete_title = "Confirm Deletion",
  arranger_popup_delete_prompt = "Are you sure you want to delete the pattern '%s'?",
  arranger_popup_save_confirm = "Save",
  arranger_popup_rename_confirm = "Rename",
  arranger_popup_delete_confirm = "Delete",
  arranger_popup_cancel = "Cancel",
  arranger_error_empty_name = "Error: Pattern name cannot be empty.",
  arranger_error_no_item_selected = "Error: Please select one or more MIDI items to save.",
  arranger_error_empty_structure = "Error: The song structure is empty. Please add at least one pattern.",
  arranger_undo_generate = "Generate Arrangement",

  -- NEW: Song Architect
  architect_section_title = "Song Architect (Structure)",
  architect_template_label = "Style Template",
  architect_btn_structure = "Create Structure (Regions)",
  architect_btn_full_song = "Generate Full Song",
  architect_clear_checkbox = "Clear Existing Regions",
  architect_clear_tracks_checkbox = "Clear Existing Tracks",
  architect_use_existing_chords_checkbox = "Use Existing Chords",
  architect_auto_mixing_checkbox = "Auto-Mixing (Volume)",
  architect_msg_beta = "Full Song Generation is coming in v3.2!\nFor now, use 'Create Structure' to set up your timeline.",

  -- Settings Tab
  midi_channel_section_title = "MIDI Channel Assignments",
  channel_chord_label = "Chords Channel",
  channel_bass_label = "Bass Channel",
  channel_melody_label = "Melody Channel",
  counter_melody_channel_info = "Counter-Melody will be on Channel %d (Melody Channel + 1).",
  channel_info_text = "Drums are always on Channel 10.",
  chord_source_section_title = "Chord Source",
  use_chord_track_checkbox = "Read chords from a specific track",
  tooltip_use_chord_track = "When enabled, creative tools will get harmony from the track specified below instead of the selected item.",
  chord_track_name_label = "Chord Track Name",
  
  -- NEW: Drum Map Section
  drum_map_section_title = "Drum Map Editor",
  drum_map_info_text = "Edit the MIDI note for each drum part (0-127).",
  drum_map_BassDrum = "Bass Drum",
  drum_map_SnareStick = "Snare Stick",
  drum_map_SnareHit = "Snare Hit",
  drum_map_Snare_Clap = "Snare/Clap",
  drum_map_SnareEdge = "Snare Edge (Rim)",
  drum_map_Tom1 = "Tom 1 (Low Floor)",
  drum_map_HiHatClosed = "Hi-Hat Closed",
  drum_map_Tom2 = "Tom 2 (High Floor)",
  drum_map_HiHatPedal = "Hi-Hat Pedal",
  drum_map_Tom3 = "Tom 3 (Low)",
  drum_map_HiHatOpen = "Hi-Hat Open",
  drum_map_MidTom = "Tom 4 (Low-Mid)",
  drum_map_Crash = "Crash 1",
  drum_map_HighTom = "Tom 5 (High)",
  drum_map_RideCrash = "Ride 1",
  drum_map_RideBell = "Ride Bell",
  drum_map_Tambourine = "Tambourine",
  drum_map_Crash2 = "Crash 2",
  drum_map_OpenHiConga = "Conga (Open Hi)",
  drum_map_LowConga = "Conga (Low)",
  drum_map_Claves = "Claves",

  -- NEW: Seed System
  seed_label = "Seed",
  seed_lock_tooltip = "Lock the current seed to reproduce the same results.",
  seed_new_tooltip = "Generate a new random seed.",

  -- Other UI
  donate_button = "Donate",
  feedback_generated = "Generated: %s %s",
  melody_error_no_chords = "No chords found. Please go to Settings and enable 'Read chords from a specific track'.",
  melody_error_no_main_melody = "Error: Could not find a main melody (on the Melody Channel) to base the counter-melody on.",
  melody_error_no_melody_to_mutate = "Error: No melody notes found on the Melody Channel to mutate.",
  bass_error_no_chords = "No chords found. Please go to Settings and enable 'Read chords from a specific track'.",
  arp_error_no_chords = "Could not find any chords in the item (or chord track) to apply Arp/Strum to.",
  rhythm_error_no_chords_found = "Error: Could not find any chords in the item to apply rhythm to.",
  add_note_error_no_notes = "Error: No notes found. Cannot add a new note.\n",
  add_note_error_no_scale = "Error: Could not detect a suitable scale. Cannot add a new note.\n",
  add_note_error_no_chords = "Error: No chords found. Cannot add a new note.\n",
  error_chord_track_not_found = "Error: Could not find a track named '%s'.",
  error_no_chords_on_track = "Error: No MIDI chords found on track '%s' within the selected item's time range.",
  error_item_not_midi_or_empty = "Error: Selected item must contain MIDI notes, or 'Read from Chord Track' must be enabled.",
  error_no_item_selected_for_action = "Error: No MIDI item selected. Please select an item before performing the '%s' action.",
  error_item_not_midi_for_action = "Error: The selected item is not MIDI. Please select a valid MIDI item for the '%s' action.",
  
  -- NEW: Custom Menu Keys
  custom_menu_button_tooltip = "Open the custom menu",
  custom_menu_popup_title = "Configure Custom Menu",
  custom_menu_popup_info = "Manage Custom Menu (Drag & drop to reorder)",
  custom_menu_add_to_root = "Add to Root",
  custom_menu_target_info = "(Click a sub-menu in the tree to select it as the target)",
  custom_menu_add_new_item_title = "Add New Item",
  custom_menu_item_type_label = "Type",
  custom_menu_item_type_action = "Action",
  custom_menu_item_type_submenu = "Sub-menu",
  custom_menu_item_type_separator = "Separator",
  custom_menu_display_name_label = "Display Name",
  custom_menu_command_id_label = "Command ID / Script ID",
  custom_menu_command_id_tooltip = "Enter the Action ID (e.g., 40001) or the script/extension ID (e.g., _RS123abc...).",
  custom_menu_add_button = "Add Item",
  custom_menu_close_button = "Close",
  custom_menu_empty = "(Menu is empty)",
  custom_menu_configure_button = "Configure Menu...",
  custom_menu_delete_button = "Delete",
  custom_menu_dnd_moving = "Moving: %s",
  custom_menu_dnd_action_label = " (Action)",
  custom_menu_dnd_submenu_label = " (Sub-menu)",
  custom_menu_dnd_separator_label = "--- Separator ---",
  
  -- NEW: Header Buttons
  smart_presets_button = "Smart Presets",
  analyze_chords_button = "Analyze Chords",
  
  -- NEW: Preset Browser Keys
  preset_browser_title = "Smart Preset Browser",
  preset_factory_vibes = "FACTORY VIBES",
  preset_user_presets = "USER PRESETS",
  preset_save_vibe = "SAVE CURRENT VIBE",
  preset_name_label = "Name:",
  preset_save_button = "Save User Preset",
  preset_saved_title = "Saved!",
  preset_saved_msg = "Preset Saved Successfully!",
  preset_tip_delete = "Tip: Right-click a User Preset to delete it.",
  preset_delete_menu = "Delete Preset",
  preset_close_button = "Close",
}

-- Vietnamese Language Table
languages['vi'] = {
  -- Window & Tabs
  window_title = 'Reanspiration - bởi Hosi (gốc. phaselab)',
  
  -- Arranger King Bridge
  ak_bridge_title = "Kết nối Arranger King",
  ak_btn_scan = "Quét Guide Track",
  ak_scan_success = "Đã đồng bộ thành công với Arranger King!",
  ak_scan_error = "Lỗi: Vui lòng chọn MIDI Item 'Guide Track' từ Arranger King trước.",
  ak_scan_failed_no_markers = "Quét thất bại: Không tìm thấy marker hoặc nốt cấu trúc trong MIDI.",

  tab_generation = "Hòa Âm",
  tab_performance = "Diễn Tấu",
  tab_creative_tools = "Sáng Tạo",
  tab_drums = "Trống",
  tab_arranger = "Sắp Xếp",
  tab_settings = "Cài Đặt",
    
  -- Drum Sequencer
  tab_drum_seq = "Drum Sequencer (Lưới Drum)",
  drum_seq_desc = "Máy Trống 32 Bước (Nốt móc kép = 2 Ô Nhịp)",
  drum_seq_clear = "Xóa Lưới",
  drum_seq_apply = "Áp dụng vào MIDI Item",
  drum_seq_load_midi = "Tải từ MIDI Item",
  drum_seq_user_preset_label = "Hòa Âm Mẫu:",
  drum_seq_new_preset = "[+] Tạo Mẫu Mới...",
  drum_seq_load_btn = "Tải",
  drum_seq_save_btn = "Lưu",
  drum_seq_delete_btn = "Xóa",
  drum_seq_save_popup_title = "Lưu Mẫu Trống",
  drum_seq_save_popup_name_label = "Tên Mẫu:",
  drum_seq_save_popup_cancel = "Hủy",
  drum_seq_factory_ptn_label = "Mẫu Có Sẵn:",
  drum_seq_select_pattern = "-- Chọn Mẫu --",
  drum_seq_hide_empty_rows = "Ẩn Hàng Trống",
  drum_seq_browse_btn = "Duyệt Mẫu",
  drum_seq_browse_title = "Browser Mẫu Trống",
  drum_seq_browse_search_hint = "Tìm kiếm mẫu...",
  drum_seq_browse_user = "Chưa phân loại",
  drum_seq_browse_user_section = "Mẫu Của Bạn",
  drum_seq_browse_lib_section = "Thư Viện Có Sẵn",
  drum_seq_browse_no_results = "Không tìm thấy mẫu nào.",
  drum_ctx_set_genre = "Gán Phân Loại",
  drum_ctx_rename = "Đổi Tên",
  drum_ctx_duplicate = "Nhân Đôi",
  drum_ctx_load = "Tải Mẫu Này",
  drum_ctx_genre_hint = "-- Chọn nhanh --",
  drum_cat_rename_title = "Đổi Tên Phân Loại:",
  drum_cat_rename_ok = "OK",
  drum_seq_preview_err = "Lỗi âm thanh: Track chưa bật Record Arm hoặc Input không phải là MIDI.",
    
  -- Generation Tab
  root_note_label = "Chủ Âm",
  tooltip_detect_scale = "Phân tích MIDI item đang chọn để tự động điền Chủ Âm và Âm Giai.",
  scale_type_label = "Loại Âm Giai",
  progression_label = "Vòng Hòa Âm",
  num_chords_label = "Số Hợp Âm",
  complexity_label = "Độ Phức Tạp",
  tooltip_complexity = "0: Hợp âm ba\n1: Hợp âm 7\n2: Hợp âm 9\n3: Hợp âm 11\n4: Hợp âm 13\n5: Hợp âm biến đổi",
  sec_dom_checkbox = "Thêm Hợp Âm Át Thứ Cấp",
  tooltip_sec_dom = "50% cơ hội chèn một hợp âm V7 của hợp âm kế tiếp (nếu đó không phải chủ âm).",
  bass_pattern_label = "Mẫu Bè Trầm (Bass)",
  tooltip_bass_pattern = "Chọn một mẫu cho bè trầm được tạo ra.",
  
  -- NEW: Bass Walking Label
  bass_walking_label = "Walking Bass (Thuật toán)",
  bass_pattern_label_creative = "Mẫu Bass",
  bass_lock_to_kick_checkbox = "Khóa theo Kick Drum",
  bass_error_no_drum_track = "Lỗi: Không tìm thấy track nào tên 'Drum'.",
  bass_error_no_kicks_found_msg = "Lỗi: Không tìm thấy Kick (Note 36) nào trong đoạn Drum.",
  
  -- NEW: Modulation Section
  mod_enable_checkbox = "Bật Chuyển Điệu (Key Change)",
  mod_target_root_label = "Chủ Âm Đích",
  mod_target_scale_label = "Âm Giai Đích",
  mod_point_label = "Chuyển tại Hợp âm #",
  mod_use_pivot_checkbox = "Sử dụng Hợp Âm Chung (Pivot)",
  tooltip_mod_use_pivot = "Cố gắng sử dụng một hợp âm chung giữa hai giọng tại điểm chuyển tiếp để tạo sự mượt mà.",
  
  -- NEW: Progression Tooltip Keys
  tooltip_progression_random = "Tạo một vòng hòa âm ngẫu nhiên dựa trên 'Số Hợp Âm'.",
  tooltip_progression_degree = "Bậc",
  tooltip_progression_duration = "Trường độ (phần của ô nhịp)",
  tooltip_progression_bass_degree = "Bass (Hợp âm Slash)",
  
  generate_button = "Tạo Hợp Âm & Bass",
  add_note_button = "Thêm Nốt",
  delete_chords_button = "Xóa Hợp Âm (Giữ Bass/Giai điệu)",
  tooltip_delete_chords = "Chỉ xóa các nốt hợp âm, giữ lại bè trầm và giai điệu đã tạo.",
  
  -- NEW: Chord Viewer Section
  chord_viewer_section_title = "Phân Tích Hợp Âm",
  chord_viewer_analyze_button = "Phân Tích & Hiển Thị Hợp Âm",
  tooltip_chord_viewer_analyze = "Phân tích MIDI trong item để phát hiện hợp âm và âm giai.",
  chord_viewer_clear_button = "Xóa",
  chord_viewer_info_text = "Hợp Âm Đã Phân Tích:",
  chord_viewer_scale_info_text = "Âm Giai Đã Phân Tích:",
  chord_viewer_success = "Đã phân tích %d hợp âm.",
  chord_viewer_error_no_chords = "Không tìm thấy hợp âm hợp lệ trong item.",
  chord_viewer_popup_title = "Các Hợp Âm Đã Phân Tích",
  chord_viewer_popup_scale_title = "Âm Giai Được Phát Hiện: %s",
  chord_viewer_popup_close_button = "Đóng",
  chord_viewer_unknown_scale = "Không rõ/Mơ hồ",
  
  -- Performance Tab
  transpose_label = "Dịch Giọng",
  spread_label = "Độ Rộng",
  tooltip_spread = "Điều chỉnh khoảng cách giữa các nốt trong hợp âm (0=Hẹp, 2=Rộng).",
  voicing_label = "Thế Đảo",
  tooltip_voicing = "Áp dụng các kỹ thuật thế đảo nâng cao (cần 4+ nốt).",
  humanize_section_title = "Tạo Cảm Giác Tự Nhiên (Humanize)",
  humanize_timing_label = "Thời Gian +/- (PPQ)",
  humanize_velocity_label = "Cường Độ +/-",
  
  -- NEW: Groove Template
  humanize_groove_label = "Mẫu Groove",
  groove_none = "Không (Ngẫu nhiên)",
  groove_8th_medium = "Swing Nốt Đơn",
  groove_16th_light = "Swing Nốt Kép",
  humanize_swing_label = "Độ Swing %", -- NEW
  humanize_accent_label = "Nhấn Phách (Accent)", -- NEW
  vel_accent_none = "Không", -- NEW
  vel_accent_strong = "Mạnh (1 & 3)", -- NEW
  vel_accent_weak = "Nhẹ (2 & 4)", -- NEW
  vel_accent_sync = "Đảo Phách (Off-beat)", -- NEW
  
  humanize_button = "Áp Dụng Humanize",
  tooltip_humanize = "Ngẫu nhiên hóa một chút về thời gian và cường độ của tất cả nốt trong item dựa trên groove đã chọn.",
  undo_humanize_button = "Hoàn Tác Humanize",

  -- Creative Tools Tab
  melody_section_title = "Tạo Giai Điệu",
  melody_contour_label = "Đường Nét",
  contour_random = "Ngẫu Nhiên",
  contour_ascending = "Đi Lên (Ascending)",
  contour_arch = "Hình Vòm (Arch)",
  contour_descending = "Đi Xuống (Descending)",
  contour_valley = "Thung Lũng (Valley)",
  contour_markov = "Chuỗi Markov",
  contour_counterpoint = "Đối Vị (Ngược Hướng)",
  contour_thematic = "Theo Chủ Đề (Motif)",
  melody_structure_label = "Cấu Trúc", -- NEW
  tooltip_melody_contour = "Thiết lập hình dạng tổng thể của giai điệu.",
  
  -- NEW: Melody Pattern Library
  melody_pattern_label = "Melody Pattern",
  melody_pattern_none = "Không (Căng/Thả)",
  
  melody_density_label = "Mật Độ Nốt",
  melody_min_oct_label = "Quãng 8 Thấp Nhất",
  melody_max_oct_label = "Quãng 8 Cao Nhất",
  melody_generate_button = "Tạo Giai Điệu",
  tooltip_melody_generate = "Tạo giai điệu dựa trên Mẫu, Motif đang hoạt động, hoặc logic Căng/Thả.",
  undo_melody_button = "Hoàn Tác Giai Điệu",

  -- Motif Keys
  melody_generate_motif_button = "Tạo Motif",
  tooltip_melody_generate_motif = "Tạo ý tưởng giai điệu (1 ô nhịp).\nSẽ được sử dụng nếu 'Mẫu Giai Điệu' là 'Không'.",
  melody_clear_motif_button = "Xóa Motif",
  melody_motif_active_text = "Motif đang hoạt động: %d nốt",
  melody_motif_tooltip_text = "Các Nốt Motif:\n%s", 
  melody_motif_cleared_text = "Đã xóa motif.",
  melody_motif_generated_text = "Đã tạo motif (%d nốt).",
  melody_motif_error_no_chords = "Không thể tạo motif: Không tìm thấy hợp âm trong item hoặc track hợp âm.",

  melody_generate_counter_button = "Tạo Giai điệu Đối đáp",
  tooltip_melody_generate_counter = "Tạo một giai điệu thứ hai dựa trên giai điệu chính.\nXóa giai điệu đối đáp đã tạo trước đó.",
  undo_counter_melody_button = "Hoàn Tác Giai điệu Đối đáp",
  
  -- NEW: Adaptive Markov Keys
  melody_markov_learn_button = "Học từ Vùng Chọn",
  tooltip_melody_markov_learn = "Phân tích giai điệu trong item đang chọn và cập nhật xác suất Markov Chain để giống phong cách đó.\nSử dụng 'Markov Chain' trong phần Đường Nét.",
  melody_markov_status_default = "Markov: Mặc định",
  melody_markov_status_learned = "Markov: Đã học từ người dùng",
  melody_markov_error_no_notes = "Lỗi: Không tìm thấy nốt giai điệu nào trong item để học.",
  
  -- NEW: Melody Mutator Section
  melody_mutator_section_title = "Biến Tấu Giai Điệu",
  melody_mutate_invert_button = "Đảo Ngược (Cao độ)",
  tooltip_melody_mutate_invert = "Đảo ngược các quãng của giai điệu (ví dụ: lên 3 thành xuống 3).",
  melody_mutate_retrograde_button = "Chạy Ngược (Retrograde)",
  tooltip_melody_mutate_retrograde = "Đảo ngược giai điệu, chơi từ cuối về đầu.",
  melody_mutate_displace_label = "Dịch Chuyển (PPQ)",
  melody_mutate_displace_button = "Dịch Tiết Tấu",
  tooltip_melody_mutate_displace = "Dịch chuyển tất cả các nốt giai điệu về trước hoặc sau một khoảng PPQ.",
  undo_melody_mutation_button = "Hoàn Tác Biến Tấu",
  
  -- NEW: Cinematic Ostinato Section
  ostinato_section_title = "Mẫu Lặp (Ostinato) Phim",
  ostinato_len_label = "Độ Dài Mẫu",
  ostinato_buildup_label = "Tăng Dần (Build-up %)",
  btn_gen_ostinato = "Tạo Ostinato",
  btn_undo_ostinato = "Hoàn Tác Ostinato",
  
  bass_section_title = "Tạo Bass",
  bass_pattern_label_creative = "Mẫu Bass##BassCreative",
  bass_generate_button = "Tạo Bass",
  tooltip_bass_generate = "Tạo một bè bass mới dựa trên các hợp âm có sẵn.\nXóa bè bass đã tạo trước đó.",
  undo_bass_button = "Hoàn Tác Bass",
  
  arp_strum_section_title = "Rải Hợp Âm / Quạt Chả (Arp/Strum)",
  arp_strum_pattern_label = "Mẫu##Arp", -- Obsolete
  arp_strum_delay_label = "Độ Trễ (PPQ)",
  arp_strum_velocity_label = "Cường Độ Đánh Lên (%)",
  tooltip_arp_strum_velocity = "Thiết lập cường độ của các lần đánh lên (up-strum) theo phần trăm của cường độ gốc.",
  arp_rate_label = "Tốc Độ Rải",
  arp_apply_button = "Áp Dụng Arp/Strum",
  tooltip_arp_apply = "Áp dụng mẫu cho các nốt được chọn (hoặc tất cả nếu không có nốt nào được chọn).",
  undo_arp_button = "Hoàn Tác Arp/Strum",
  
  -- NEW KEYS FOR ARP/STRUM SPLIT
  mode_none = "Không",
  mode_arp = "Rải Đơn (Arpeggiator)",
  mode_strum = "Quạt Chả (Strummer)",
  perform_mode_label = "Chế Độ",
  arp_pattern_label = "Mẫu Rải",
  strum_pattern_label = "Mẫu Quạt",
  tooltip_strum_pattern = "Chọn một mẫu Strumming từ thư viện.",
  
  -- NEW: Arp Euclidean
  arp_euclidean_enable_checkbox = "Sử dụng Nhịp Euclid",
  arp_euclidean_steps_label = "Số Bước Euclid",
  arp_euclidean_hits_label = "Số Nốt Euclid",
  
  -- NEW: Guitar Strumming Keys
  strum_palm_mute_checkbox = "Kỹ thuật Palm Mute",
  strum_guitar_voicing_checkbox = "Thế bấm Guitar (Dây buông)",
  strum_up_stroke_sf_label = "Độ trễ Quạt lên (Up-stroke)",
  
  rhythm_section_title = "Ứng Dụng Tiết Tấu (Rhythm)",
  rhythm_pattern_label = "Mẫu Tiết Tấu",
  rhythm_apply_button = "Áp Dụng Tiết Tấu",
  tooltip_rhythm_apply = "Áp dụng mẫu tiết tấu đã chọn lên các hợp âm.",
  undo_rhythm_button = "Hoàn Tác Tiết Tấu",

  -- Drums Tab
  drum_pattern_label = "Mẫu Trống",
  drum_generate_button = "Tạo Trống",
  tooltip_drum_generate = "Tạo một bản beat trống cho toàn bộ độ dài item.\nXoá các nốt trống đã tạo trước đó.",
  drum_generate_fill_button = "Tạo Drum Fill",
  tooltip_drum_generate_fill = "Tạo Drum Fill trong ô nhịp cuối cùng của item.",
  drum_generate_variation_button = "Tạo Biến Thể",
  tooltip_drum_generate_variation = "Ngẫu nhiên thêm/xóa một số nốt Kick/Hi-Hat khỏi mẫu trống hiện tại.",
  drum_error_no_chords = "Vui lòng tạo hợp âm hoặc có nốt MIDI trong item trước.",
  
  -- NEW: Euclidean Sequencer Section
  euclidean_section_title = "Bộ Tạo Nhịp Euclid",
  euclidean_instrument_label = "Nhạc Cụ",
  euclidean_steps_label = "Số Bước (1/16)",
  euclidean_hits_label = "Số Nốt (Hits)",
  euclidean_rotation_label = "Xoay (Rotation)",
  euclidean_generate_button = "Tạo Lớp Nhịp",
  tooltip_euclidean_generate = "Tạo một lớp nhịp điệu cho nhạc cụ đã chọn sử dụng thuật toán Euclid.\nSẽ thay thế các nốt cũ của nhạc cụ này.",

  -- Arranger Tab
  arranger_section_title = "Sắp Xếp Dự Án",
  arranger_sync_button = "Đồng bộ từ Vùng (Region)",
  arranger_sync_tooltip = "Đọc tất cả các Region từ dự án Reaper hiện tại và điền vào danh sách bên dưới.",
  arranger_structure_title = "Cấu Trúc Bài Hát (Regions)",
  arranger_col_id = "ID",
  arranger_col_name = "Tên",
  arranger_col_energy = "Năng Lượng",
  arranger_col_pos = "Bắt đầu",
  arranger_col_len = "Độ dài",
  arranger_col_actions = "Hành động",
  arranger_action_glue = "Gộp",
  arranger_btn_glue_all = "Gộp Tất Cả",
  arranger_state_glued = "✓ Đã Gộp",
  arranger_info_text = "Sử dụng Region trong REAPER để định nghĩa các phần của bài hát (Verse, Chorus, v.v.).",
  arranger_no_regions = "Không tìm thấy region nào trong dự án.",
  
  arranger_pool_title = "Thư Viện Mẫu (Pattern)",
  arranger_save_button = "Lưu Item thành Mẫu",
  arranger_state_glued = "✓ Đã Gộp",
  expression_section_title = "Động Cơ Biểu Cảm (Expression)",
  expression_dynamics_label = "Độ Mạnh (%)",
  expression_follow_pitch_checkbox = "Theo Cao Độ (Swell)",
  expression_breath_checkbox = "Thở (Giảm cuối câu)",
  expression_legato_label = "Chồng Nốt (Overlap ms)",
  expression_smart_pedal_checkbox = "Pedal Thông Minh",
  expression_apply_button = "Áp Dụng Biểu Cảm",
  undo_expression_button = "Hoàn Tác Biểu Cảm",
  tooltip_expression_dynamics = "Điều chỉnh phạm vi biến thiên của Modulation/Expression.",
  tooltip_expression_breath = "Tự động giảm Expression ở cuối mỗi câu nhạc để tạo cảm giác thở.",
  arranger_rename_button = "Đổi Tên",
  arranger_delete_button = "Xóa",
  arranger_add_button = "Thêm",
  arranger_move_up_button = "Lên",
  arranger_move_down_button = "Xuống",
  arranger_remove_button = "Loại Bỏ",
  arranger_output_track_label = "Tên Track Output",
  arranger_regions_checkbox = "Tạo Vùng (Region) cho mỗi phần",
  arranger_generate_button = "TẠO BẢN PHỐI",
  arranger_popup_savename_title = "Lưu Mẫu Mới",
  arranger_popup_savename_prompt = "Nhập tên cho mẫu mới:",
  arranger_popup_renamename_title = "Đổi Tên Mẫu",
  arranger_popup_rename_prompt = "Nhập tên mới:",
  arranger_popup_delete_title = "Xác Nhận Xóa",
  arranger_popup_delete_prompt = "Bạn có chắc muốn xóa mẫu '%s' không?",
  arranger_popup_save_confirm = "Lưu",
  arranger_popup_rename_confirm = "Đổi Tên",
  arranger_popup_delete_confirm = "Xóa",
  arranger_popup_cancel = "Hủy",
  arranger_error_empty_name = "Lỗi: Tên mẫu không được để trống.",
  arranger_error_no_item_selected = "Lỗi: Vui lòng chọn một hoặc nhiều item MIDI để lưu.",
  arranger_error_empty_structure = "Lỗi: Cấu trúc bài hát đang trống. Vui lòng thêm ít nhất một mẫu.",
  arranger_undo_generate = "Tạo Bản Phối",

  -- NEW: Song Architect
  architect_section_title = "Kiến Trúc Sư Bài Hát (Cấu Trúc)",
  architect_template_label = "Mẫu Cấu Trúc",
  architect_btn_structure = "Tạo Cấu Trúc (Regions)",
  architect_btn_full_song = "Tạo Cả Bài (Full Song)",
  architect_clear_checkbox = "Xóa Các Region Cũ",
  architect_clear_tracks_checkbox = "Xóa Các Track Cũ",
  architect_use_existing_chords_checkbox = "Dùng Hợp Âm Có Sẵn",
  architect_auto_mixing_checkbox = "Tự Động Mix (Volume)",
  architect_msg_beta = "Tính năng 'Tạo Cả Bài' sẽ ra mắt trong v3.2!\nHãy dùng 'Tạo Cấu Trúc' để dựng khung timeline trước.",

  -- Settings Tab
  midi_channel_section_title = "Phân Kênh MIDI",
  channel_chord_label = "Kênh Hợp Âm",
  channel_bass_label = "Kênh Bass",
  channel_melody_label = "Kênh Giai Điệu",
  counter_melody_channel_info = "Giai điệu Đối đáp sẽ ở Kênh %d (Kênh Giai điệu + 1).",
  channel_info_text = "Trống luôn được đặt ở Kênh 10.",
  chord_source_section_title = "Nguồn Hợp Âm",
  use_chord_track_checkbox = "Đọc hợp âm từ một track chỉ định",
  tooltip_use_chord_track = "Khi bật, các công cụ sáng tạo sẽ lấy hòa âm từ track được chỉ định bên dưới thay vì từ item đang chọn.",
  chord_track_name_label = "Tên Track Hợp Âm",

  -- NEW: Drum Map Section
  drum_map_section_title = "Trình Chỉnh Sửa Drum Map",
  drum_map_info_text = "Chỉnh sửa nốt MIDI cho từng bộ phận trống (0-127).",
  drum_map_BassDrum = "Trống Kick (Bass Drum)",
  drum_map_SnareStick = "Trống Lẫy (Snare Stick)",
  drum_map_SnareHit = "Trống Lẫy (Snare Hit)",
  drum_map_Snare_Clap = "Trống Lẫy/Vỗ Tay (Clap)",
  drum_map_SnareEdge = "Trống Lẫy (Rimshot)",
  drum_map_Tom1 = "Tom 1 (Sàn Thấp)",
  drum_map_HiHatClosed = "Hi-Hat Đóng",
  drum_map_Tom2 = "Tom 2 (Sàn Cao)",
  drum_map_HiHatPedal = "Hi-Hat Đạp",
  drum_map_Tom3 = "Tom 3 (Thấp)",
  drum_map_HiHatOpen = "Hi-Hat Mở",
  drum_map_MidTom = "Tom 4 (Trung Thấp)",
  drum_map_Crash = "Crash 1",
  drum_map_HighTom = "Tom 5 (Cao)",
  drum_map_RideCrash = "Ride 1",
  drum_map_RideBell = "Chuông Ride",
  drum_map_Tambourine = "Tambourine",
  drum_map_Crash2 = "Crash 2",
  drum_map_OpenHiConga = "Conga (Mở Cao)",
  drum_map_LowConga = "Conga (Thấp)",
  drum_map_Claves = "Claves",

  -- NEW: Seed System
  seed_label = "Seed (Hạt giống)",
  seed_lock_tooltip = "Khóa seed hiện tại để tái tạo lại kết quả giống hệt.",
  seed_new_tooltip = "Tạo một seed ngẫu nhiên mới.",

  -- Other UI
  donate_button = "Ủng Hộ",
  feedback_generated = "Đã tạo: %s %s",
  melody_error_no_chords = "Không tìm thấy hợp âm. Vui lòng vào Tab Cài Đặt và chọn 'Đọc hợp âm từ một track chỉ định'.",
  melody_error_no_main_melody = "Lỗi: Không tìm thấy giai điệu chính (trên Kênh Giai điệu) để làm cơ sở tạo giai điệu đối đáp.",
  melody_error_no_melody_to_mutate = "Lỗi: Không tìm thấy nốt giai điệu nào trên Kênh Giai điệu để biến tấu.",
  bass_error_no_chords = "Không tìm thấy hợp âm. Vui lòng vào Tab Cài Đặt và chọn 'Đọc hợp âm từ một track chỉ định'.",
  arp_error_no_chords = "Không tìm thấy hợp âm nào trong item (hoặc track hợp âm) để áp dụng Arp/Strum.",
  rhythm_error_no_chords_found = "Lỗi: Không tìm thấy hợp âm nào trong item để áp dụng tiết tấu.",
  add_note_error_no_notes = "Lỗi: Không tìm thấy nốt nhạc. Không thể thêm nốt mới.\n",
  add_note_error_no_scale = "Lỗi: Không thể nhận diện âm giai phù hợp. Không thể thêm nốt mới.\n",
  add_note_error_no_chords = "Lỗi: Không tìm thấy hợp âm. Không thể thêm nốt mới.\n",
  error_chord_track_not_found = "Lỗi: Không tìm thấy track nào có tên '%s'.",
  error_no_chords_on_track = "Lỗi: Không tìm thấy hợp âm MIDI nào trên track '%s' trong khoảng thời gian của item đang chọn.",
  error_item_not_midi_or_empty = "Lỗi: Item được chọn phải chứa nốt MIDI, hoặc phải bật chức năng 'Đọc từ Track Hợp Âm'.",
  error_no_item_selected_for_action = "Lỗi: Chưa chọn item MIDI. Vui lòng chọn một item MIDI trước khi thực hiện hành động '%s'.",
  error_item_not_midi_for_action = "Lỗi: Item đã chọn không phải là MIDI. Vui lòng chọn một item MIDI hợp lệ cho hành động '%s'.",
  
  -- NEW: Custom Menu Keys
  custom_menu_button_tooltip = "Mở menu tùy chỉnh",
  custom_menu_popup_title = "Cấu Hình Menu Tùy Chỉnh",
  custom_menu_popup_info = "Quản lý Menu (Kéo & thả để sắp xếp)",
  custom_menu_add_to_root = "Thêm vào Gốc",
  custom_menu_target_info = "(Nhấp vào menu con trong cây để chọn làm mục tiêu)",
  custom_menu_add_new_item_title = "Thêm Mục Mới",
  custom_menu_item_type_label = "Loại",
  custom_menu_item_type_action = "Hành động (Action)",
  custom_menu_item_type_submenu = "Menu con (Sub-menu)",
  custom_menu_item_type_separator = "Dấu ngăn cách (Separator)",
  custom_menu_display_name_label = "Tên Hiển Thị",
  custom_menu_command_id_label = "Command ID / Script ID",
  custom_menu_command_id_tooltip = "Nhập Action ID (ví dụ: 40001) hoặc script/extension ID (ví dụ: _RS123abc...).",
  custom_menu_add_button = "Thêm Mục",
  custom_menu_close_button = "Đóng",
  custom_menu_empty = "(Menu đang trống)",
  custom_menu_configure_button = "Cấu hình Menu...",
  custom_menu_delete_button = "Xóa",
  custom_menu_dnd_moving = "Đang di chuyển: %s",
  custom_menu_dnd_action_label = " (Hành động)",
  custom_menu_dnd_submenu_label = " (Menu con)",
  custom_menu_dnd_separator_label = "--- Dấu ngăn cách ---",
  
  -- NEW: Header Buttons
  smart_presets_button = "Hòa Âm Mẫu (Smart Presets)",
  analyze_chords_button = "Phân Tích Hợp Âm",

  -- NEW: Preset Browser Keys
  preset_browser_title = "Thư Viện Hòa Âm Mẫu",
  preset_factory_vibes = "HÒA ÂM MẪU (FACTORY)",
  preset_user_presets = "HÒA ÂM NGƯỜI DÙNG",
  preset_save_vibe = "LƯU CÀI ĐẶT HIỆN TẠI",
  preset_name_label = "Tên:",
  preset_save_button = "Lưu Hòa Âm Mới",
  preset_saved_title = "Đã Lưu!",
  preset_saved_msg = "Lưu hòa âm thành công!",
  preset_tip_delete = "Mẹo: Chuột phải vào hòa âm người dùng để xóa.",
  preset_delete_menu = "Xóa Hòa Âm",
  preset_close_button = "Đóng",
  
  -- NEW: Expression Engine
  expression_section_title = "Động Cơ Biểu Cảm (Expression)",
  expression_dynamics_label = "Độ Mạnh (%)",
  expression_follow_pitch_checkbox = "Theo Cao Độ (Swell)",
  expression_breath_checkbox = "Thở (Giảm cuối câu)",
  expression_legato_label = "Chồng Nốt (Overlap ms)",
  expression_smart_pedal_checkbox = "Pedal Thông Minh",
  expression_apply_button = "Áp Dụng Biểu Cảm",
  undo_expression_button = "Hoàn Tác Biểu Cảm",
  tooltip_expression_dynamics = "Điều chỉnh phạm vi biến thiên của Modulation/Expression.",
  tooltip_expression_breath = "Tự động giảm Expression ở cuối mỗi câu nhạc để tạo cảm giác thở.",
}

-- Japanese Language Table
languages['ja'] = {
  -- Window & Tabs
  window_title = 'Reanspiration - 作 Hosi (原案 phaselab)',
  
  -- Arranger King Bridge
  ak_bridge_title = "Arranger King ブリッジ",
  ak_btn_scan = "ガイドトラックをスキャン",
  ak_scan_success = "Arranger Kingと正常に同期しました！",
  ak_scan_error = "エラー: 最初にArranger Kingガイドトラック(MIDI)を選択してください。",
  ak_scan_failed_no_markers = "スキャン失敗: MIDI内にテキストマーカーまたは構造ノートが見つかりません。",
  
  tab_generation = "生成",
  tab_performance = "演奏",
  tab_creative_tools = "創作ツール",
  tab_drums = "ドラム",
  tab_arranger = "アレンジャー",
  tab_settings = "設定",
    
  -- Drum Sequencer
  tab_drum_seq = "ドラムシーケンサー",
  drum_seq_desc = "32ステップドラムマシン (16分音符 = 2小節)",
  drum_seq_clear = "グリッドをクリア",
  drum_seq_apply = "MIDIアイテムに適用",
  drum_seq_load_midi = "MIDIアイテムから読み込む",
  drum_seq_user_preset_label = "ユーザープリセット:",
  drum_seq_new_preset = "[+] 新規プリセット...",
  drum_seq_load_btn = "読み込む",
  drum_seq_save_btn = "保存",
  drum_seq_delete_btn = "削除",
  drum_seq_save_popup_title = "ドラムプリセットを保存",
  drum_seq_save_popup_name_label = "プリセット名:",
  drum_seq_save_popup_cancel = "キャンセル",
  drum_seq_factory_ptn_label = "プリセット:",
  drum_seq_select_pattern = "-- パターンを選択 --",
  drum_seq_hide_empty_rows = "空の行を隠す",
  drum_seq_browse_btn = "プリセットを閉覧",
  drum_seq_browse_title = "ドラムプリセットブラウザ",
  drum_seq_browse_search_hint = "プリセットを検索...",
  drum_seq_browse_user = "未分類",
  drum_seq_browse_user_section = "ユーザープリセット",
  drum_seq_browse_lib_section = "内蔵ライブラリ",
  drum_seq_browse_no_results = "プリセットが見つかりません。",
  drum_ctx_set_genre = "ジャンルを設定",
  drum_ctx_rename = "名前変更",
  drum_ctx_duplicate = "複製",
  drum_ctx_load = "パターンをロード",
  drum_ctx_genre_hint = "-- クイック選択 --",
  drum_cat_rename_title = "カテゴリ名変更:",
  drum_cat_rename_ok = "OK",
  drum_seq_preview_err = "プレビューエラー: トラックの録音待機が無効か、MIDI入力が設定されていません。",

  -- Generation Tab
  root_note_label = "ルート音",
  tooltip_detect_scale = "選択したMIDIアイテムを分析し、ルート音とスケールタイプを自動設定します。",
  scale_type_label = "スケールタイプ",
  progression_label = "コード進行",
  num_chords_label = "コード数",
  complexity_label = "複雑さ",
  tooltip_complexity = "0: 三和音\n1: 7thコード\n2: 9thコード\n3: 11thコード\n4: 13thコード\n5: オルタード",
  sec_dom_checkbox = "セカンダリードミナントを追加",
  tooltip_sec_dom = "次のコード（トニックでない場合）のV7を50%の確率で挿入します。",
  bass_pattern_label = "ベースパターン",
  tooltip_bass_pattern = "生成されるベースラインのパターンを選択します。",
  
  -- NEW: Bass Walking Label
  bass_walking_label = "ウォーキングベース (アルゴリズム)",
  bass_pattern_label_creative = "ベースパターン",
  bass_lock_to_kick_checkbox = "キックドラムにロック (Lock to Kick)",
  bass_error_no_drum_track = "エラー: 'Drum'という名前のトラックが見つかりません。",
  bass_error_no_kicks_found_msg = "エラー: ドラムトラックにキック(Note 36)が見つかりません。",
  
  -- NEW: Modulation Section
  mod_enable_checkbox = "転調を有効化 (Key Change)",
  mod_target_root_label = "ターゲットルート",
  mod_target_scale_label = "ターゲットスケール",
  mod_point_label = "転調するコード番号 #",
  mod_use_pivot_checkbox = "ピボットコードを使用",
  tooltip_mod_use_pivot = "両方のキーに共通するコードを転調ポイントで使用し、スムーズな移行を図ります。",
  
  -- NEW: Progression Tooltip Keys
  tooltip_progression_random = "「コード数」に基づいてランダムなコード進行を生成します。",
  tooltip_progression_degree = "度数",
  tooltip_progression_duration = "長さ (小節の割合)",
  tooltip_progression_bass_degree = "ベース音 (スラッシュコード)",
  
  generate_button = "コードとベースを生成",
  add_note_button = "ノートを追加",
  delete_chords_button = "コードを削除 (ベース/メロディは維持)",
  tooltip_delete_chords = "生成されたベースラインとメロディを維持したまま、コードノートを削除します。",
  
  -- NEW: Chord Viewer Section
  chord_viewer_section_title = "コードビューア",
  chord_viewer_analyze_button = "コードを分析して表示",
  tooltip_chord_viewer_analyze = "アイテム内のMIDIを分析し、コードとスケールを検出します。",
  chord_viewer_clear_button = "クリア",
  chord_viewer_info_text = "分析されたコード:",
  chord_viewer_scale_info_text = "分析されたスケール:",
  chord_viewer_success = "%d 個のコードを分析しました。",
  chord_viewer_error_no_chords = "アイテムに有効なコードが見つかりません。",
  chord_viewer_popup_title = "分析されたコード",
  chord_viewer_popup_scale_title = "検出されたスケール: %s",
  chord_viewer_popup_close_button = "閉じる",
  chord_viewer_unknown_scale = "不明/あいまい",
  
  -- Performance Tab
  transpose_label = "移調",
  spread_label = "スプレッド",
  tooltip_spread = "コードノート間の間隔を制御します (0=狭い, 2=広い)。",
  voicing_label = "ボイシング",
  tooltip_voicing = "高度なボイシング技術を適用します（4つ以上のノートが必要）。",
  humanize_section_title = "ヒューマナイズ",
  humanize_timing_label = "タイミング +/- (PPQ)",
  humanize_velocity_label = "ベロシティ +/-",
  
  -- NEW: Groove Template
  humanize_groove_label = "グルーブテンプレート",
  groove_none = "なし (ランダム)",
  groove_8th_medium = "8分音符スウィング",
  groove_16th_light = "16分音符スウィング",
  humanize_swing_label = "スウィング %", -- NEW
  humanize_accent_label = "アクセント (強弱)", -- NEW
  vel_accent_none = "なし", -- NEW
  vel_accent_strong = "強拍 (1 & 3)", -- NEW
  vel_accent_weak = "弱拍 (2 & 4)", -- NEW
  vel_accent_sync = "シンコペーション", -- NEW
  
  humanize_button = "ノートをヒューマナイズ",
  tooltip_humanize = "選択されたグルーブに基づき、アイテム内のすべてのノートのタイミングとベロシティをわずかにランダム化します。",
  undo_humanize_button = "ヒューマナイズを元に戻す",

  -- Creative Tools Tab
  melody_section_title = "メロディ生成",
  melody_contour_label = "輪郭",
  contour_random = "ランダム",
  contour_ascending = "上昇 (Ascending)",
  contour_arch = "アーチ (Arch)",
  contour_descending = "下降 (Descending)",
  contour_valley = "谷型 (Valley)",
  contour_markov = "マルコフ連鎖 (Markov)",
  contour_counterpoint = "対位法 (反行)",
  contour_thematic = "主題 (Motif)",
  melody_structure_label = "構造", -- NEW
  tooltip_melody_contour = "メロディ全体の形状を設定します。",
  
  -- NEW: Melody Pattern Library
  melody_pattern_label = "メロディパターン",
  melody_pattern_none = "なし (緊張/緩和)",
  
  melody_density_label = "密度",
  melody_min_oct_label = "最低オクターブ",
  melody_max_oct_label = "最高オクターブ",
  melody_generate_button = "メロディを生成",
  tooltip_melody_generate = "選択したパターン、アクティブなモチーフ、または緊張/緩和ロジックに基づいてメロディを生成します。",
  undo_melody_button = "メロディを元に戻す",

  -- Motif Keys
  melody_generate_motif_button = "モチーフを生成",
  tooltip_melody_generate_motif = "最初のコードに基づいて1小節のメロディアイデアを生成します。\n「メロディパターン」が「なし」の場合に使用されます。",
  melody_clear_motif_button = "モチーフをクリア",
  melody_motif_active_text = "アクティブなモチーフ: %d ノート",
  melody_motif_tooltip_text = "モチーフのノート:\n%s", 
  melody_motif_cleared_text = "モチーフをクリアしました。",
  melody_motif_generated_text = "モチーフを生成しました (%d ノート)。",
  melody_motif_error_no_chords = "モチーフを生成できません: アイテムまたはコードトラックにコードが見つかりません。",
  
  melody_generate_counter_button = "対旋律を生成",
  tooltip_melody_generate_counter = "主旋律に基づいて第二のメロディを生成します。\n以前の対旋律は削除されます。",
  undo_counter_melody_button = "対旋律を元に戻す",
  
  -- NEW: Adaptive Markov Keys
  melody_markov_learn_button = "選択範囲から学習",
  tooltip_melody_markov_learn = "選択したアイテムのメロディを分析し、そのスタイルに合わせてマルコフ連鎖の確率を更新します。\n輪郭で「Markov Chain」を使用してください。",
  melody_markov_status_default = "Markov: デフォルト",
  melody_markov_status_learned = "Markov: 学習済み",
  melody_markov_error_no_notes = "エラー: 学習対象のメロディノートが選択アイテムに見つかりません。",

  -- NEW: Melody Mutator Section
  melody_mutator_section_title = "メロディ変奏",
  melody_mutate_invert_button = "音程を反転",
  tooltip_melody_mutate_invert = "メロディの音程を最初のノートを軸に反転させます。",
  melody_mutate_retrograde_button = "逆行",
  tooltip_melody_mutate_retrograde = "メロディを逆再生します（最後から最初へ）。",
  melody_mutate_displace_label = "移動 (PPQ)",
  melody_mutate_displace_button = "リズムを移動",
  tooltip_melody_mutate_displace = "すべてのメロディノートを指定したPPQ量だけ前後にシフトします。",
  undo_melody_mutation_button = "変奏を元に戻す",
  
  -- NEW: Cinematic Ostinato Section
  ostinato_section_title = "シネマティック・オスティナート",
  ostinato_len_label = "パターン長",
  ostinato_buildup_label = "ビルドアップ (%)",
  btn_gen_ostinato = "オスティナート生成",
  btn_undo_ostinato = "オスティナートを元に戻す",
  
  bass_section_title = "ベース生成",
  bass_pattern_label_creative = "パターン##BassCreative",
  bass_generate_button = "ベースを生成",
  tooltip_bass_generate = "既存のコードの上に新しいベースラインを生成します。\n以前のベースラインは削除されます。",
  undo_bass_button = "ベースを元に戻す",
  
  arp_strum_section_title = "アルペジエーター / ストラマー",
  arp_strum_pattern_label = "パターン##Arp", -- Obsolete
  arp_strum_delay_label = "ストラム遅延 (PPQ)",
  arp_strum_velocity_label = "アップストラムのベロシティ (%)",
  tooltip_arp_strum_velocity = "アップストラムのベロシティを元のノートのベロシティに対するパーセンテージで設定します。",
  arp_rate_label = "アルペジオレート",
  arp_apply_button = "アルペジオ/ストラムを適用",
  tooltip_arp_apply = "選択したノート（選択がない場合はすべて）にパターンを適用します。",
  undo_arp_button = "アルペジオ/ストラムを元に戻す",
  
  -- NEW KEYS FOR ARP/STRUM SPLIT
  mode_none = "なし",
  mode_arp = "アルペジエーター",
  mode_strum = "ストラマー",
  perform_mode_label = "モード",
  arp_pattern_label = "アルペジオパターン",
  strum_pattern_label = "ストラムパターン",
  tooltip_strum_pattern = "ライブラリからストラミングパターンを選択します。",
  
  -- NEW: Arp Euclidean
  arp_euclidean_enable_checkbox = "ユークリッドリズムを使用",
  arp_euclidean_steps_label = "Euc ステップ",
  arp_euclidean_hits_label = "Euc ヒット",
  
  -- NEW: Guitar Strumming Keys
  strum_palm_mute_checkbox = "パームミュート (Palm Mute)",
  strum_guitar_voicing_checkbox = "ギターボイシング (オープン)",
  strum_up_stroke_sf_label = "アップストローク遅延",
  
  rhythm_section_title = "リズムアプリケーター",
  rhythm_pattern_label = "リズムパターン",
  rhythm_apply_button = "リズムを適用",
  tooltip_rhythm_apply = "選択したリズムパターンをコードに適用します。",
  undo_rhythm_button = "リズムを元に戻す",

  -- Drums Tab
  drum_pattern_label = "ドラムパターン",
  drum_generate_button = "ドラムを生成",
  tooltip_drum_generate = "アイテム全体の長さのドラムビートを生成します。\n以前のドラムノートは削除されます。",
  drum_generate_fill_button = "フィルを生成",
  tooltip_drum_generate_fill = "アイテムの最後の小節にドラムフィルを生成します。",
  drum_generate_variation_button = "バリエーションを作成",
  tooltip_drum_generate_variation = "現在のドラムパターンからキック/ハイハットのノートをランダムにいくつか追加/削除します。",
  drum_error_no_chords = "最初にコードを生成するか、アイテム内にMIDIノートを配置してください。",

  -- NEW: Euclidean Sequencer Section
  euclidean_section_title = "ユークリッド・シーケンサー",
  euclidean_instrument_label = "楽器",
  euclidean_steps_label = "ステップ数 (16分)",
  euclidean_hits_label = "ヒット数",
  euclidean_rotation_label = "回転 (Rotation)",
  euclidean_generate_button = "レイヤーを生成",
  tooltip_euclidean_generate = "ユークリッドアルゴリズムを使用して、選択した楽器のリズムレイヤーを生成します。\nこの楽器の既存のノートのみを置き換えます。",

  -- Arranger Tab
  arranger_section_title = "プロジェクト・アレンジャー",
  arranger_sync_button = "プロジェクト・リージョンから同期",
  arranger_sync_tooltip = "現在のReaperプロジェクトからすべてのリージョンを読み込み、下のリストに表示します。",
  arranger_structure_title = "曲の構成 (リージョン)",
  arranger_col_id = "ID",
  arranger_col_name = "名前",
  arranger_col_energy = "エナジー",
  arranger_col_pos = "開始",
  arranger_col_len = "長さ",
  arranger_col_actions = "アクション",
  arranger_action_glue = "接着 (Glue)",
  arranger_btn_glue_all = "すべてのリージョンを結合",
  arranger_info_text = "REAPERのリージョンを使用して、曲のセクション（バース、コーラスなど）を定義します。",
  arranger_no_regions = "プロジェクトにリージョンが見つかりません。",
  
  arranger_pool_title = "パターン プール",
  arranger_save_button = "アイテムをパターンとして保存",
  arranger_rename_button = "名前の変更",
  arranger_delete_button = "削除",
  arranger_add_button = "追加",
  arranger_move_up_button = "上へ",
  arranger_move_down_button = "下へ",
  arranger_remove_button = "削除",
  arranger_output_track_label = "出力トラック名",
  arranger_regions_checkbox = "セクションごとにリージョンを作成",
  arranger_generate_button = "アレンジを生成",
  arranger_popup_savename_title = "新しいパターンを保存",
  arranger_popup_savename_prompt = "新しいパターンの名前を入力してください:",
  arranger_popup_renamename_title = "パターンの名前を変更",
  arranger_popup_rename_prompt = "新しい名前を入力してください:",
  arranger_popup_delete_title = "削除の確認",
  arranger_popup_delete_prompt = "本当にパターン '%s' を削除しますか？",
  arranger_popup_save_confirm = "保存",
  arranger_popup_rename_confirm = "変更",
  arranger_popup_delete_confirm = "削除",
  arranger_popup_cancel = "キャンセル",
  arranger_error_empty_name = "エラー：パターン名を空にすることはできません。",
  arranger_error_no_item_selected = "エラー：保存するMIDIアイテムを1つ以上選択してください。",
  arranger_error_empty_structure = "エラー：曲の構成が空です。少なくとも1つのパターンを追加してください。",
  arranger_undo_generate = "アレンジを生成",

  -- NEW: Song Architect
  architect_section_title = "ソング・アーキテクト（構成）",
  architect_template_label = "スタイルテンプレート",
  architect_btn_structure = "構成を作成 (Regions)",
  architect_btn_full_song = "全曲生成 (Full Song)",
  architect_clear_checkbox = "既存のリージョンを削除",
  architect_clear_tracks_checkbox = "既存のトラックを削除",
  architect_use_existing_chords_checkbox = "既存のコードを使用",
  architect_auto_mixing_checkbox = "自動ミキシング (音量)",
  architect_msg_beta = "全曲生成機能はv3.2で登場予定！\n今は「構成を作成」を使ってタイムラインを設定してください。",

  -- Settings Tab
  midi_channel_section_title = "MIDIチャンネル設定",
  channel_chord_label = "コードチャンネル",
  channel_bass_label = "ベースチャンネル",
  channel_melody_label = "メロディチャンネル",
  counter_melody_channel_info = "対旋律はチャンネル %d (メロディチャンネル + 1) になります。",
  channel_info_text = "ドラムは常にチャンネル10です。",
  chord_source_section_title = "コードソース",
  use_chord_track_checkbox = "特定のトラックからコードを読み取る",
  tooltip_use_chord_track = "有効にすると、クリエイティブツールは選択したアイテムの代わりに以下のトラックからハーモニーを取得します。",
  chord_track_name_label = "コードトラック名",
  
  -- NEW: Drum Map Section
  drum_map_section_title = "ドラムマップエディタ",
  drum_map_info_text = "各ドラムパートのMIDIノートを編集します (0-127)。",
  drum_map_BassDrum = "バスドラム",
  drum_map_SnareStick = "スネアスティック",
  drum_map_SnareHit = "スネアヒット",
  drum_map_Snare_Clap = "スネア/クラップ",
  drum_map_SnareEdge = "スネアエッジ (リム)",
  drum_map_Tom1 = "タム 1 (ローフロア)",
  drum_map_HiHatClosed = "クローズドハイハット",
  drum_map_Tom2 = "タム 2 (ハイフロア)",
  drum_map_HiHatPedal = "ハイハットペダル",
  drum_map_Tom3 = "タム 3 (ロー)",
  drum_map_HiHatOpen = "オープンハイハット",
  drum_map_MidTom = "タム 4 (ローミッド)",
  drum_map_Crash = "クラッシュ 1",
  drum_map_HighTom = "タム 5 (ハイ)",
  drum_map_RideCrash = "ライド 1",
  drum_map_RideBell = "ライドベル",
  drum_map_Tambourine = "タンバリン",
  drum_map_Crash2 = "クラッシュ 2",
  drum_map_OpenHiConga = "コンガ (オープンハイ)",
  drum_map_LowConga = "コンガ (ロー)",
  drum_map_Claves = "クラーベ",

  -- NEW: Seed System
  seed_label = "シード (Seed)",
  seed_lock_tooltip = "現在のシードをロックして結果を再現します。",
  seed_new_tooltip = "新しいランダムシードを生成します。",

  -- Other UI
  donate_button = "寄付",
  feedback_generated = "生成: %s %s",
  melody_error_no_chords = "コードが見つかりません。設定タブで「特定のトラックからコードを読み取る」を有効にしてください。",
  melody_error_no_main_melody = "エラー: 対旋律の基になる主旋律（メロディチャンネル上）が見つかりません。",
  melody_error_no_melody_to_mutate = "エラー: 変奏するメロディノートがメロディチャンネルに見つかりません。",
  bass_error_no_chords = "コードが見つかりません。設定タブで「特定のトラックからコードを読み取る」を有効にしてください。",
  arp_error_no_chords = "アイテム内（またはコードトラック）にアルペジオ/ストラムを適用するコードが見つかりませんでした。",
  rhythm_error_no_chords_found = "エラー：リズムを適用するためのコードがアイテム内に見つかりませんでした。",
  add_note_error_no_notes = "エラー: ノートが見つかりません。新しいノートを追加できません。\n",
  add_note_error_no_scale = "エラー: 適切なスケールを検出できませんでした。新しいノートを追加できません。\n",
  add_note_error_no_chords = "エラー: コードが見つかりません。新しいノートを追加できません。\n",
  error_chord_track_not_found = "エラー: '%s' という名前のトラックが見つかりませんでした。",
  error_no_chords_on_track = "エラー: 選択したアイテムの時間範囲内に、トラック '%s' にMIDIコードが見つかりませんでした。",
  error_item_not_midi_or_empty = "エラー: 選択したアイテムにはMIDIノートが含まれているか、「コードトラックから読み取る」を有効にする必要があります。",
  error_no_item_selected_for_action = "エラー：MIDIアイテムが選択されていません。'%s' アクションを実行する前にアイテムを選択してください。",
  error_item_not_midi_for_action = "エラー：選択されたアイテムはMIDIではありません。'%s' アクションには有効なMIDIアイテムを選択してください。",
  
  -- NEW: Custom Menu Keys
  custom_menu_button_tooltip = "カスタムメニューを開く",
  custom_menu_popup_title = "カスタムメニューの設定",
  custom_menu_popup_info = "カスタムメニューの管理 (ドラッグ＆ドロップで並び替え)",
  custom_menu_add_to_root = "ルートに追加",
  custom_menu_target_info = "(ターゲットとしてツリー内のサブメニューをクリック)",
  custom_menu_add_new_item_title = "新しい項目を追加",
  custom_menu_item_type_label = "タイプ",
  custom_menu_item_type_action = "アクション",
  custom_menu_item_type_submenu = "サブメニュー",
  custom_menu_item_type_separator = "区切り線",
  custom_menu_display_name_label = "表示名",
  custom_menu_command_id_label = "コマンドID / スクリプトID",
  custom_menu_command_id_tooltip = "アクションID (例: 40001) またはスクリプト/拡張ID (例: _RS123abc...) を入力します。",
  custom_menu_add_button = "項目を追加",
  custom_menu_close_button = "閉じる",
  custom_menu_empty = "(メニューは空です)",
  custom_menu_configure_button = "メニューを設定...",
  custom_menu_delete_button = "削除",
  custom_menu_dnd_moving = "移動中: %s",
  custom_menu_dnd_action_label = " (アクション)",
  custom_menu_dnd_submenu_label = " (サブメニュー)",
  custom_menu_dnd_separator_label = "--- セパレーター ---",
  
  -- NEW: Header Buttons
  smart_presets_button = "スマートプリセット",
  analyze_chords_button = "コード分析",

  -- NEW: Preset Browser Keys
  preset_browser_title = "スマートプリセットブラウザ",
  preset_factory_vibes = "ファクトリープリセット",
  preset_user_presets = "ユーザープリセット",
  preset_save_vibe = "現在の設定を保存",
  preset_name_label = "名前:",
  preset_save_button = "ユーザープリセットを保存",
  preset_saved_title = "保存完了!",
  preset_saved_msg = "プリセットが正常に保存されました。",
  preset_tip_delete = "ヒント: ユーザープリセットを右クリックして削除できます。",
  preset_delete_menu = "プリセットを削除",
  preset_close_button = "閉じる",

  -- NEW: Expression Engine
  expression_section_title = "ダイナミック表現エンジン",
  expression_dynamics_label = "強弱 (Dynamics %)",
  expression_follow_pitch_checkbox = "ピッチに追従 (Swell)",
  expression_breath_checkbox = "ブレス (フレーズ終わりの減衰)",
  expression_legato_label = "レガート・オーバーラップ (ms)",
  expression_smart_pedal_checkbox = "スマート・サスティンペダル",
  expression_apply_button = "表現を適用",
  undo_expression_button = "表現を元に戻す",
  tooltip_expression_dynamics = "CC1/CC11モジュレーションの範囲を制御します。",
  tooltip_expression_breath = "フレーズの終わりで表現を自動的に下げ、呼吸をシミュレートします。",
}

-- Chinese (Simplified) Language Table
languages['zh'] = {
  -- Window & Tabs
  window_title = 'Reanspiration - 作者 Hosi (原创 phaselab)',
  
  -- Arranger King Bridge
  ak_bridge_title = "Arranger King 桥接",
  ak_btn_scan = "扫描向导轨道 (Guide Track)",
  ak_scan_success = "已成功与 Arranger King 同步！",
  ak_scan_error = "错误：请先选择 Arranger King 向导轨道 (MIDI)。",
  ak_scan_failed_no_markers = "扫描失败：在MIDI中未找到文本标记或结构音符。",
  
  tab_generation = "生成",
  tab_performance = "演奏",
  tab_creative_tools = "创意工具",
  tab_drums = "鼓",
  tab_arranger = "编曲器",
  tab_settings = "设置",
    
  -- Drum Sequencer
  tab_drum_seq = "鼓音序器",
  drum_seq_desc = "32步鼓机 (16分音符 = 2小节)",
  drum_seq_clear = "清除网格",
  drum_seq_apply = "应用于 MIDI 项目",
  drum_seq_load_midi = "从 MIDI 项目载入",
  drum_seq_user_preset_label = "用户预设:",
  drum_seq_new_preset = "[+] 新建预设...",
  drum_seq_load_btn = "载入",
  drum_seq_save_btn = "保存",
  drum_seq_delete_btn = "删除",
  drum_seq_save_popup_title = "保存鼓点预设",
  drum_seq_save_popup_name_label = "预设名称:",
  drum_seq_save_popup_cancel = "取消",
  drum_seq_factory_ptn_label = "内置模式:",
  drum_seq_select_pattern = "-- 选择模式 --",
  drum_seq_hide_empty_rows = "隐藏空行",
  drum_seq_browse_btn = "浏览预设",
  drum_seq_browse_title = "鼓模式浏览器",
  drum_seq_browse_search_hint = "搜索预设...",
  drum_seq_browse_user = "未分类",
  drum_seq_browse_user_section = "用户预设",
  drum_seq_browse_lib_section = "内置库",
  drum_seq_browse_no_results = "未找到匹配预设。",
  drum_ctx_set_genre = "设置分类",
  drum_ctx_rename = "重命名",
  drum_ctx_duplicate = "复制",
  drum_ctx_load = "加载此模式",
  drum_ctx_genre_hint = "-- 快速选择 --",
  drum_cat_rename_title = "重命名类别:",
  drum_cat_rename_ok = "OK",
  drum_seq_preview_err = "预览错误: 轨道待机录音(Record Arm)未启用或输入不是MIDI。",
    
  -- Generation Tab
  root_note_label = "根音",
  tooltip_detect_scale = "分析所选MIDI项目以自动设置根音和音阶类型。",
  scale_type_label = "音阶类型",
  progression_label = "和弦进行",
  num_chords_label = "和弦数量",
  complexity_label = "复杂度",
  tooltip_complexity = "0: 三和弦\n1: 七和弦\n2: 九和弦\n3: 十一和弦\n4: 十三和弦\n5: 变化和弦",
  sec_dom_checkbox = "添加次属和弦",
  tooltip_sec_dom = "有50%的几率在下一个和弦（如果不是主和弦）前插入其V7和弦。",
  bass_pattern_label = "贝斯模式",
  tooltip_bass_pattern = "为生成的贝斯声部选择模式。",
  
  -- NEW: Bass Walking Label
  bass_walking_label = "行走贝斯 (算法生成)",
  bass_pattern_label_creative = "贝斯模式",
  bass_lock_to_kick_checkbox = "锁定到底鼓 (Lock to Kick)",
  bass_error_no_drum_track = "错误：未找到名为 'Drum' 的轨道。",
  bass_error_no_kicks_found_msg = "错误：在鼓分轨中未找到底鼓 (Note 36)。",
  
  -- NEW: Modulation Section
  mod_enable_checkbox = "启用转调 (Key Change)",
  mod_target_root_label = "目标根音",
  mod_target_scale_label = "目标音阶",
  mod_point_label = "转调点 (和弦序号)",
  mod_use_pivot_checkbox = "使用枢轴和弦 (Pivot)",
  tooltip_mod_use_pivot = "尝试在过渡点使用两个调之间的共同和弦，以实现平滑过渡。",
  
  -- NEW: Progression Tooltip Keys
  tooltip_progression_random = "根据“和弦数量”生成随机的和弦进行。",
  tooltip_progression_degree = "级数",
  tooltip_progression_duration = "持续时间 (小节的分数)",
  tooltip_progression_bass_degree = "贝斯音 (斜线和弦)",
  
  generate_button = "生成和弦与贝斯",
  add_note_button = "添加音符",
  delete_chords_button = "删除和弦 (保留贝斯/旋律)",
  tooltip_delete_chords = "删除和弦音符，同时保留已生成的贝斯和旋律。",
  
  -- NEW: Chord Viewer Section
  chord_viewer_section_title = "和弦查看器",
  chord_viewer_analyze_button = "分析并显示和弦",
  tooltip_chord_viewer_analyze = "分析项目中的 MIDI 以检测和弦和音阶。",
  chord_viewer_clear_button = "清除",
  chord_viewer_info_text = "已分析的和弦:",
  chord_viewer_scale_info_text = "已分析的音阶:",
  chord_viewer_success = "%d 个和弦。",
  chord_viewer_error_no_chords = "项目中未找到有效和弦。",
  chord_viewer_popup_title = "已分析的和弦",
  chord_viewer_popup_scale_title = "检测到的音阶: %s",
  chord_viewer_popup_close_button = "关闭",
  chord_viewer_unknown_scale = "未知/模糊",
  
  -- Performance Tab
  transpose_label = "移调",
  spread_label = "分布",
  tooltip_spread = "控制和弦音符之间的间距 (0=紧凑, 2=开放)。",
  voicing_label = "声部配置",
  tooltip_voicing = "应用高级声部配置技巧（需要4个以上音符）。",
  humanize_section_title = "人性化",
  humanize_timing_label = "时间 +/- (PPQ)",
  humanize_velocity_label = "力度 +/-",
  
  -- NEW: Groove Template
  humanize_groove_label = "律动模板",
  groove_none = "无 (随机)",
  groove_8th_medium = "8分音符摇摆",
  groove_16th_light = "16分音符摇摆",
  humanize_swing_label = "摇摆 %", -- NEW
  humanize_accent_label = "力度重音", -- NEW
  vel_accent_none = "无", -- NEW
  vel_accent_strong = "强拍 (1 & 3)", -- NEW
  vel_accent_weak = "弱拍 (2 & 4)", -- NEW
  vel_accent_sync = "切分音 (Off-beat)", -- NEW
  
  humanize_button = "人性化音符",
  tooltip_humanize = "根据所选律动，对项目中的所有音符的时间和力度进行轻微的随机化处理。",
  undo_humanize_button = "撤销人性化",

  -- Creative Tools Tab
  melody_section_title = "旋律生成",
  melody_contour_label = "轮廓",
  contour_random = "随机",
  contour_ascending = "上行 (Ascending)",
  contour_arch = "杂形 (Arch)",
  contour_descending = "下行 (Descending)",
  contour_valley = "谷型 (Valley)",
  contour_markov = "马尔可夫链条",
  contour_counterpoint = "对位 (反向)",
  contour_thematic = "主题 (Motif)",
  melody_structure_label = "结构",
  tooltip_melody_contour = "设置旋律的整体形状。",
  
  -- NEW: Melody Pattern Library
  melody_pattern_label = "旋律模式",
  melody_pattern_none = "无 (紧张/松弛)",
  
  melody_density_label = "密度",
  melody_min_oct_label = "最低八度",
  melody_max_oct_label = "最高八度",
  melody_generate_button = "生成旋律",
  tooltip_melody_generate = "根据所选模式、活动主题或 紧张/松弛 逻辑生成旋律。",
  undo_melody_button = "撤销旋律",

  -- Motif Keys
  melody_generate_motif_button = "生成主题",
  tooltip_melody_generate_motif = "基于第一个和弦生成一个1小节的旋律创意。\n如果“旋律模式”设置为“无”，将使用此主题。",
  melody_clear_motif_button = "清除主题",
  melody_motif_active_text = "活动主题: %d 音符",
  melody_motif_tooltip_text = "主题音符:\n%s", 
  melody_motif_cleared_text = "主题已清除。",
  melody_motif_generated_text = "主题已生成 (%d 音符)。",
  melody_motif_error_no_chords = "无法生成主题：在项目或和弦轨道中未找到和弦。",
  
  melody_generate_counter_button = "生成对位旋律",
  tooltip_melody_generate_counter = "基于主旋律生成第二旋律。\n将删除之前生成的任何对位旋律。",
  undo_counter_melody_button = "撤销对位旋律",
  
  -- NEW: Adaptive Markov Keys
  melody_markov_learn_button = "从选区学习",
  tooltip_melody_markov_learn = "分析所选项目中的旋律，并更新马尔可夫链概率以匹配其风格。\n请在轮廓中选择“Markov Chain”。",
  melody_markov_status_default = "Markov: 默认",
  melody_markov_status_learned = "Markov: 已从用户学习",
  melody_markov_error_no_notes = "错误：在选定项目中未找到可学习的旋律音符。",

  -- NEW: Melody Mutator Section
  melody_mutator_section_title = "旋律变化器",
  melody_mutate_invert_button = "音高反转",
  tooltip_melody_mutate_invert = "围绕第一个音符反转旋律的音程。",
  melody_mutate_retrograde_button = "逆行（反向）",
  tooltip_melody_mutate_retrograde = "反转旋律，从后往前播放。",
  melody_mutate_displace_label = "位移 (PPQ)",
  melody_mutate_displace_button = "节奏位移",
  tooltip_melody_mutate_displace = "将所有旋律音符按指定的PPQ值向前或向后移动。",
  undo_melody_mutation_button = "撤销变化",
  
  -- NEW: Cinematic Ostinato Section
  ostinato_section_title = "电影固定音型 (Ostinato)",
  ostinato_len_label = "模式长度",
  ostinato_buildup_label = "渐强 (%)",
  btn_gen_ostinato = "生成固定音型",
  btn_undo_ostinato = "撤销固定音型",

  bass_section_title = "贝斯生成",
  bass_pattern_label_creative = "模式##BassCreative",
  bass_generate_button = "生成贝斯",
  tooltip_bass_generate = "在现有和弦上生成新的贝斯声部。\n将删除之前生成的任何贝斯声部。",
  undo_bass_button = "撤销贝斯",
  
  arp_strum_section_title = "琶音/扫弦",
  arp_strum_pattern_label = "模式##Arp", -- Obsolete
  arp_strum_delay_label = "扫弦延迟 (PPQ)",
  arp_strum_velocity_label = "上扫力度 (%)",
  tooltip_arp_strum_velocity = "将上扫的力度设置为原始音符力度的百分比。",
  arp_rate_label = "琶音速率",
  arp_apply_button = "应用琶音/扫弦",
  tooltip_arp_apply = "将模式应用于选定的音符（如果未选择，则应用于所有音符）。",
  undo_arp_button = "撤销琶音/扫弦",
  
  -- NEW KEYS FOR ARP/STRUM SPLIT
  mode_none = "无",
  mode_arp = "琶音 (Arp)",
  mode_strum = "扫弦 (Strum)",
  perform_mode_label = "模式",
  arp_pattern_label = "琶音模式",
  strum_pattern_label = "扫弦模式",
  tooltip_strum_pattern = "从库中选择一个扫弦模式。",
  
  -- NEW: Arp Euclidean
  arp_euclidean_enable_checkbox = "使用欧几里得节奏",
  arp_euclidean_steps_label = "步数",
  arp_euclidean_hits_label = "击打数",
  
  -- NEW: Guitar Strumming Keys
  strum_palm_mute_checkbox = "闷音 (Palm Mute)",
  strum_guitar_voicing_checkbox = "吉他声部 (开放弦)",
  strum_up_stroke_sf_label = "上扫延迟比例",
  
  rhythm_section_title = "节奏应用器",
  rhythm_pattern_label = "节奏模式",
  rhythm_apply_button = "应用节奏",
  tooltip_rhythm_apply = "将选定的节奏模式应用于和弦。",
  undo_rhythm_button = "撤销节奏",

  -- Drums Tab
  drum_pattern_label = "鼓模式",
  drum_generate_button = "生成鼓",
  tooltip_drum_generate = "为整个项目长度生成鼓点。\n将删除之前生成的任何鼓音符。",
  drum_generate_fill_button = "生成加花 (Fill)",
  tooltip_drum_generate_fill = "在项目的最后一个小节中生成鼓加花。",
  drum_generate_variation_button = "创建变奏",
  tooltip_drum_generate_variation = "从当前的鼓模式中随机添加/删除一些底鼓/踩镲音符。",
  drum_error_no_chords = "请先生成和弦或在项目中有MIDI音符。",

  -- NEW: Euclidean Sequencer Section
  euclidean_section_title = "欧几里得音序器",
  euclidean_instrument_label = "乐器",
  euclidean_steps_label = "步数 (16分)",
  euclidean_hits_label = "击打数 (Hits)",
  euclidean_rotation_label = "回転 (Rotation)",
  euclidean_generate_button = "生成层",
  tooltip_euclidean_generate = "使用欧几里得算法为所选乐器生成节奏层。\n仅替换此乐器的现有音符。",

  -- Arranger Tab
  arranger_section_title = "项目编曲器",
  arranger_sync_button = "从项目区域同步",
  arranger_sync_tooltip = "读取当前 Reaper 项目中的所有区域并填充下面的列表。",
  arranger_structure_title = "歌曲结构 (区域)",
  arranger_col_id = "ID",
  arranger_col_name = "名称",
  arranger_col_energy = "能量",
  arranger_col_pos = "开始",
  arranger_col_len = "长度",
  arranger_col_actions = "操作",
  arranger_action_glue = "胶水 (Glue)",
  arranger_btn_glue_all = "合并所有区域",
  arranger_state_glued = "✓ 已合并",
  arranger_info_text = "使用 REAPER 中的区域来定义歌曲段落（主歌、副歌等）。",
  arranger_no_regions = "项目中未找到区域。",
  
  arranger_pool_title = "模板库",
  arranger_save_button = "将项目另存为模板",
  arranger_rename_button = "重命名",
  arranger_delete_button = "删除",
  arranger_add_button = "添加",
  arranger_move_up_button = "上移",
  arranger_move_down_button = "下移",
  arranger_remove_button = "移除",
  arranger_output_track_label = "输出轨道名称",
  arranger_regions_checkbox = "为每个部分创建区域",
  arranger_generate_button = "生成编曲",
  arranger_popup_savename_title = "保存新模板",
  arranger_popup_savename_prompt = "为新模板输入名称:",
  arranger_popup_renamename_title = "重命名模板",
  arranger_popup_rename_prompt = "输入新名称:",
  arranger_popup_delete_title = "确认删除",
  arranger_popup_delete_prompt = "您确定要删除模板“%s”吗？",
  arranger_popup_save_confirm = "保存",
  arranger_popup_rename_confirm = "重命名",
  arranger_popup_delete_confirm = "删除",
  arranger_popup_cancel = "取消",
  arranger_error_empty_name = "错误：模板名称不能为空。",
  arranger_error_no_item_selected = "错误：请选择一个或多个MIDI项目以保存。",
  arranger_error_empty_structure = "错误：歌曲结构为空。请至少添加一个模板。",
  arranger_undo_generate = "生成编曲",

  -- NEW: Song Architect
  architect_section_title = "歌曲架构师 (结构)",
  architect_template_label = "风格模板",
  architect_btn_structure = "创建结构 (Regions)",
  architect_btn_full_song = "生成整首歌曲",
  architect_clear_checkbox = "清除现有区域 (Region)",
  architect_clear_tracks_checkbox = "清除现有轨道",
  architect_use_existing_chords_checkbox = "使用现有和弦",
  architect_auto_mixing_checkbox = "自动混音 (音量)",
  architect_msg_beta = "“生成整首歌曲”功能将在 v3.2 版本推出！\n目前请使用“创建结构”来搭建时间线框架。",

  -- Settings Tab
  midi_channel_section_title = "MIDI通道分配",
  channel_chord_label = "和弦通道",
  channel_bass_label = "贝斯通道",
  channel_melody_label = "旋律通道",
  counter_melody_channel_info = "对位旋律将在通道 %d (旋律通道 + 1)。",
  channel_info_text = "鼓组始终在通道10。",
  chord_source_section_title = "和弦来源",
  use_chord_track_checkbox = "从特定轨道读取和弦",
  tooltip_use_chord_track = "启用后，创意工具将从下面指定的轨道获取和声，而不是从选定的项目。",
  chord_track_name_label = "和弦轨道名称",

  -- NEW: Drum Map Section
  drum_map_section_title = "鼓点映射编辑器",
  drum_map_info_text = "编辑每个鼓声部的MIDI音符 (0-127)。",
  drum_map_BassDrum = "底鼓",
  drum_map_SnareStick = "军鼓(鼓棒)",
  drum_map_SnareHit = "军鼓",
  drum_map_Snare_Clap = "军鼓/拍手",
  drum_map_SnareEdge = "军鼓(鼓边)",
  drum_map_Tom1 = "嗵鼓 1 (低落地)",
  drum_map_HiHatClosed = "闭合踩镲",
  drum_map_Tom2 = "嗵鼓 2 (高落地)",
  drum_map_HiHatPedal = "踩镲(踏板)",
  drum_map_Tom3 = "嗵鼓 3 (低)",
  drum_map_HiHatOpen = "开镲",
  drum_map_MidTom = "嗵鼓 4 (中低)",
  drum_map_Crash = "镲片 1",
  drum_map_HighTom = "嗵鼓 5 (高)",
  drum_map_RideCrash = "叮叮镲 1",
  drum_map_RideBell = "叮叮镲(镲帽)",
  drum_map_Tambourine = "铃鼓",
  drum_map_Crash2 = "镲片 2",
  drum_map_OpenHiConga = "康加鼓 (高)",
  drum_map_LowConga = "康加鼓 (低)",
  drum_map_Claves = "音棒",

  -- NEW: Seed System
  seed_label = "种子 (Seed)",
  seed_lock_tooltip = "锁定当前种子以重现结果。",
  seed_new_tooltip = "生成新的随机种子。",

  -- Other UI
  donate_button = "捐赠",
  feedback_generated = "已生成: %s %s",
  melody_error_no_chords = "未找到和弦。请转到“设置”并启用“从特定轨道读取和弦”。",
  melody_error_no_main_melody = "错误：找不到（旋律通道上的）主旋律来作为对位旋律的基础。",
  melody_error_no_melody_to_mutate = "错误：在旋律通道上找不到可用于变化的旋律音符。",
  bass_error_no_chords = "未找到和弦。请转到“设置”并启用“从特定轨道读取和弦”。",
  arp_error_no_chords = "在项目（或和弦轨道）中找不到可应用琶音/扫弦的和弦。",
  rhythm_error_no_chords_found = "错误：在项目中找不到可应用节奏的和弦。",
  add_note_error_no_notes = "错误：找不到音符。无法添加新音符。\n",
  add_note_error_no_scale = "错误：无法检测到合适的音阶。无法添加新音符。\n",
  add_note_error_no_chords = "错误：找不到和弦。无法添加新音符。\n",
  error_chord_track_not_found = "错误：找不到名为“%s”的轨道。",
  error_no_chords_on_track = "错误：在选定项目的时间范围内，在轨道“%s”上找不到MIDI和弦。",
  error_item_not_midi_or_empty = "错误：选定的项目必须包含MIDI音符，或者必须启用“从和弦轨道读取”。",
  error_no_item_selected_for_action = "错误：未选择MIDI项目。请在执行“%s”操作前选择一个项目。",
  error_item_not_midi_for_action = "错误：所选项目不是MIDI。请为“%s”操作选择一个有效的 MIDI 项目。",
  
  -- NEW: Custom Menu Keys
  custom_menu_button_tooltip = "打开自定义菜单",
  custom_menu_popup_title = "配置自定义菜单",
  custom_menu_popup_info = "菜单管理 (拖放排序)",
  custom_menu_add_to_root = "添加到根目录",
  custom_menu_target_info = "(点击树中的子菜单以选定为目标)",
  custom_menu_add_new_item_title = "添加新项目",
  custom_menu_item_type_label = "类型",
  custom_menu_item_type_action = "操作 (Action)",
  custom_menu_item_type_submenu = "子菜单 (Sub-menu)",
  custom_menu_item_type_separator = "分隔符 (Separator)",
  custom_menu_display_name_label = "显示名称",
  custom_menu_command_id_label = "命令ID / 脚本ID",
  custom_menu_command_id_tooltip = "输入操作ID (例如 40001) 或 脚本/扩展ID (例如 _RS123abc...).",
  custom_menu_add_button = "添加项目",
  custom_menu_close_button = "关闭",
  custom_menu_empty = "(菜单为空)",
  custom_menu_configure_button = "配置菜单...",
  custom_menu_delete_button = "删除",
  custom_menu_dnd_moving = "正在移动: %s",
  custom_menu_dnd_action_label = " (操作)",
  custom_menu_dnd_submenu_label = " (子菜单)",
  custom_menu_dnd_separator_label = "--- 分隔符 ---",
  
  -- NEW: Header Buttons
  smart_presets_button = "智能预设",
  analyze_chords_button = "分析和弦",

  -- NEW: Preset Browser Keys
  preset_browser_title = "智能预设浏览器",
  preset_factory_vibes = "工厂预设",
  preset_user_presets = "用户预设",
  preset_save_vibe = "保存当前设置",
  preset_name_label = "名称:",
  preset_save_button = "保存用户预设",
  preset_saved_title = "已保存!",
  preset_saved_msg = "预设保存成功！",
  preset_tip_delete = "提示：右键点击用户预设可将其删除。",
  preset_delete_menu = "删除预设",
  preset_close_button = "关闭",
}

-- Korean Language Table
languages['ko'] = {
  -- Window & Tabs
  window_title = 'Reanspiration - 제작 Hosi (원안 phaselab)',
  
  -- Arranger King Bridge
  ak_bridge_title = "Arranger King 브리지",
  ak_btn_scan = "가이드 트랙 스캔",
  ak_scan_success = "Arranger King과 성공적으로 동기화되었습니다!",
  ak_scan_error = "오류: 먼저 Arranger King 가이드 트랙(MIDI)을 선택하십시오.",
  ak_scan_failed_no_markers = "스캔 실패: MIDI에서 텍스트 마커 또는 구조 노트를 찾을 수 없습니다.",
  
  tab_generation = "생성",
  tab_performance = "연주",
  tab_creative_tools = "창작 도구",
  tab_drums = "드럼",
  tab_arranger = "편곡기",
  tab_settings = "설정",
    
  -- Drum Sequencer
  tab_drum_seq = "드럼 시퀀서",
  drum_seq_desc = "32스텝 드럼 머신 (16분 음표 = 2마디)",
  drum_seq_clear = "그리드 지우기",
  drum_seq_apply = "MIDI 아이템에 적용",
  drum_seq_load_midi = "MIDI 아이템에서 불러오기",
  drum_seq_user_preset_label = "사용자 프리셋:",
  drum_seq_new_preset = "[+] 새 프리셋...",
  drum_seq_load_btn = "불러오기",
  drum_seq_save_btn = "저장",
  drum_seq_delete_btn = "삭제",
  drum_seq_save_popup_title = "드럼 프리셋 저장",
  drum_seq_save_popup_name_label = "프리셋 이름:",
  drum_seq_save_popup_cancel = "취소",
  drum_seq_factory_ptn_label = "기본 패턴:",
  drum_seq_select_pattern = "-- 패턴 선택 --",
  drum_seq_hide_empty_rows = "빈 행 숨기기",
  drum_seq_browse_btn = "프리셋 살펴보기",
  drum_seq_browse_title = "드럼 프리셋 브라우저",
  drum_seq_browse_search_hint = "프리셋 검색...",
  drum_seq_browse_user = "미분류",
  drum_seq_browse_user_section = "사용자 프리셋",
  drum_seq_browse_lib_section = "내장 라이브러리",
  drum_seq_browse_no_results = "프리셋을 찾을 수 없습니다.",
  drum_ctx_set_genre = "장르 설정",
  drum_ctx_rename = "이름 바꾸기",
  drum_ctx_duplicate = "복제",
  drum_ctx_load = "패턴 로드",
  drum_ctx_genre_hint = "-- 빠른 선택 --",
  drum_cat_rename_title = "카테고리 이름 바꾸기:",
  drum_cat_rename_ok = "OK",
  drum_seq_preview_err = "미리보기 오류: 트랙의 Record Arm이 꺼져있거나 MIDI 입력이 아닙니다。",

  -- Generation Tab
  root_note_label = "루트 음",
  tooltip_detect_scale = "선택한 MIDI 항목을 분석하여 루트 음과 스케일 종류를 자동으로 설정합니다.",
  scale_type_label = "스케일 종류",
  progression_label = "코드 진행",
  num_chords_label = "코드 수",
  complexity_label = "복잡도",
  tooltip_complexity = "0: 3화음\n1: 7화음\n2: 9화음\n3: 11화음\n4: 13화음\n5: 얼터드",
  sec_dom_checkbox = "세컨더리 도미넌트 추가",
  tooltip_sec_dom = "다음 코드(토닉이 아닌 경우)의 V7을 50% 확률로 삽입합니다.",
  bass_pattern_label = "베이스 패턴",
  tooltip_bass_pattern = "생성된 베이스 라인의 패턴을 선택합니다.",
  
  -- NEW: Bass Walking Label
  bass_walking_label = "워킹 베이스 (알고리즘)",
  bass_pattern_label_creative = "베이스 패턴",
  bass_lock_to_kick_checkbox = "킥 드럼에 고정 (Lock to Kick)",
  bass_error_no_drum_track = "오류: 'Drum' 이름의 트랙을 찾을 수 없습니다.",
  bass_error_no_kicks_found_msg = "오류: 드럼 트랙에서 킥(Note 36)을 찾을 수 없습니다.",
  
  -- NEW: Modulation Section
  mod_enable_checkbox = "전조 활성화 (Key Change)",
  mod_target_root_label = "목표 루트",
  mod_target_scale_label = "목표 스케일",
  mod_point_label = "전조 지점 (코드 번호 #)",
  mod_use_pivot_checkbox = "피벗 코드 사용",
  tooltip_mod_use_pivot = "부드러운 전환을 위해 전조 지점에서 두 키의 공통 코드를 사용합니다.",
  
  -- NEW: Progression Tooltip Keys
  tooltip_progression_random = "'코드 수'를 기반으로 무작위 코드 진행을 생성합니다.",
  tooltip_progression_degree = "근음",
  tooltip_progression_duration = "길이 (마디의 비율)",
  tooltip_progression_bass_degree = "베이스 음 (슬래시 코드)",
  
  generate_button = "코드 및 베이스 생성",
  add_note_button = "음표 추가",
  delete_chords_button = "코드 삭제 (베이스/멜로디 유지)",
  tooltip_delete_chords = "생성된 베이스 라인과 멜로디는 유지하고 코드 음표만 삭제합니다.",
  
  -- NEW: Chord Viewer Section
  chord_viewer_section_title = "코드 뷰어",
  chord_viewer_analyze_button = "코드 분석 및 표시",
  tooltip_chord_viewer_analyze = "항목의 MIDI를 분석하여 코드와 스케일을 감지합니다.",
  chord_viewer_clear_button = "지우기",
  chord_viewer_info_text = "분석된 코드:",
  chord_viewer_scale_info_text = "분석된 스케일:",
  chord_viewer_success = "%d개의 코드를 분석했습니다.",
  chord_viewer_error_no_chords = "항목에서 유효한 코드를 찾을 수 없습니다.",
  chord_viewer_popup_title = "분석된 코드",
  chord_viewer_popup_scale_title = "감지된 스케일: %s",
  chord_viewer_popup_close_button = "닫기",
  chord_viewer_unknown_scale = "알 수 없음/모호함",
  
  -- Performance Tab
  transpose_label = "조옮김",
  spread_label = "펼침",
  tooltip_spread = "코드 음표 간의 간격을 조절합니다 (0=좁게, 2=넓게).",
  voicing_label = "보이싱",
  tooltip_voicing = "고급 보이싱 기법을 적용합니다 (4개 이상의 음표 필요).",
  humanize_section_title = "인간화",
  humanize_timing_label = "타이밍 +/- (PPQ)",
  humanize_velocity_label = "벨로시티 +/-",
  
  -- NEW: Groove Template
  humanize_groove_label = "그루브 템플릿",
  groove_none = "없음 (랜덤)",
  groove_8th_medium = "8분음표 스윙",
  groove_16th_light = "16분음표 스윙",
  humanize_swing_label = "스윙 %", -- NEW
  humanize_accent_label = "벨로시티 악센트", -- NEW
  vel_accent_none = "없음", -- NEW
  vel_accent_strong = "강박 (1 & 3)", -- NEW
  vel_accent_weak = "약박 (2 & 4)", -- NEW
  vel_accent_sync = "당김음 (Off-beat)", -- NEW
  
  humanize_button = "음표 인간화",
  tooltip_humanize = "선택한 그루브에 따라 항목의 모든 음표의 타이밍과 벨로시티를 약간 무작위화합니다.",
  undo_humanize_button = "인간화 취소",

  -- Creative Tools Tab
  melody_section_title = "멜로디 생성",
  melody_contour_label = "윤곽",
  contour_counterpoint = "대위법 (반진행)", -- NEW
  melody_structure_label = "구조", -- NEW
  tooltip_melody_contour = "멜로디의 전체적인 모양을 설정합니다.",
  
  -- NEW: Guitar Strumming Keys
  strum_palm_mute_checkbox = "팜 뮤트 (Palm Mute)",
  strum_guitar_voicing_checkbox = "기타 보이싱 (오픈 스트링)",
  strum_up_stroke_sf_label = "업 스트로크 지연 비율",
  
  -- NEW: Melody Pattern Library
  melody_pattern_label = "멜로디 패턴",
  melody_pattern_none = "없음 (긴장/이완)",
  
  melody_density_label = "밀도",
  melody_min_oct_label = "최저 옥타브",
  melody_max_oct_label = "최고 옥타브",
  melody_generate_button = "멜로디 생성",
  tooltip_melody_generate = "선택한 패턴, 활성 모티프 또는 긴장/이완 로직에 따라 멜로디를 생성합니다.",
  undo_melody_button = "멜로디 취소",

  -- Motif Keys
  melody_generate_motif_button = "모티프 생성",
  tooltip_melody_generate_motif = "첫 번째 코드를 기반으로 1마디 멜로디 아이디어를 생성합니다.\n'멜로디 패턴'이 '없음'으로 설정된 경우 사용됩니다.",
  melody_clear_motif_button = "모티프 지우기",
  melody_motif_active_text = "활성 모티프: %d 음표",
  melody_motif_tooltip_text = "모티프 음표:\n%s", 
  melody_motif_cleared_text = "모티프를 지웠습니다.",
  melody_motif_generated_text = "모티프를 생성했습니다 (%d 음표).",
  melody_motif_error_no_chords = "모티프를 생성할 수 없습니다: 항목 또는 코드 트랙에서 코드를 찾을 수 없습니다.",
  
  melody_generate_counter_button = "대선율 생성",
  tooltip_melody_generate_counter = "주선율을 기반으로 두 번째 멜로디를 생성합니다.\n이전 대선율은 삭제됩니다.",
  undo_counter_melody_button = "대선율 취소",
  
  -- NEW: Adaptive Markov Keys
  melody_markov_learn_button = "선택 영역에서 학습",
  tooltip_melody_markov_learn = "선택한 항목의 멜로디를 분석하고 마르코프 체인 확률을 업데이트하여 스타일을 일치시킵니다.\n윤곽에서 'Markov Chain'을 사용하십시오.",
  melody_markov_status_default = "Markov: 기본값",
  melody_markov_status_learned = "Markov: 사용자로부터 학습됨",
  melody_markov_error_no_notes = "오류: 선택한 항목에서 학습할 멜로디 음표를 찾을 수 없습니다.",

  -- NEW: Melody Mutator Section
  melody_mutator_section_title = "멜로디 변형",
  melody_mutate_invert_button = "음정 반전",
  tooltip_melody_mutate_invert = "첫 번째 음을 기준으로 멜로디의 음정을 반전시킵니다.",
  melody_mutate_retrograde_button = "역행 (반대)",
  tooltip_melody_mutate_retrograde = "멜로디를 거꾸로 재생합니다 (끝에서 처음으로).",
  melody_mutate_displace_label = "이동 (PPQ)",
  melody_mutate_displace_button = "리듬 이동",
  tooltip_melody_mutate_displace = "모든 멜로디 음표를 지정된 PPQ만큼 앞뒤로 이동시킵니다.",
  undo_melody_mutation_button = "변형 취소",
  
  -- NEW: Cinematic Ostinato Section
  ostinato_section_title = "시네마틱 오스티나토",
  ostinato_len_label = "패턴 길이",
  ostinato_buildup_label = "빌드업 (%)",
  btn_gen_ostinato = "오스티나토 생성",
  btn_undo_ostinato = "오스티나토 실행 취소",
  
  bass_section_title = "베이스 생성",
  bass_pattern_label_creative = "패턴##BassCreative",
  bass_generate_button = "베이스 생성",
  tooltip_bass_generate = "기존 코드 위에 새로운 베이스라인을 생성합니다.\n이전에 생성된 베이스는 삭제됩니다.",
  undo_bass_button = "베이스 취소",

  arp_strum_section_title = "아르페지에이터 / 스트러머",
  arp_strum_pattern_label = "패턴##Arp", -- Obsolete
  arp_strum_delay_label = "스트럼 딜레이 (PPQ)",
  arp_strum_velocity_label = "업 스트럼 벨로시티 (%)",
  tooltip_arp_strum_velocity = "업 스트럼의 벨로시티를 원래 음표 벨로시티의 백분율로 설정합니다.",
  arp_rate_label = "아르페지오 속도",
  arp_apply_button = "아르페지오/스트럼 적용",
  tooltip_arp_apply = "선택한 음표(선택이 없으면 전체)에 패턴을 적용합니다.",
  undo_arp_button = "아르페지오/스트럼 취소",
  
  -- NEW KEYS FOR ARP/STRUM SPLIT
  mode_none = "없음",
  mode_arp = "아르페지에이터",
  mode_strum = "스트러머",
  perform_mode_label = "모드",
  arp_pattern_label = "아르페지오 패턴",
  strum_pattern_label = "스트럼 패턴",
  tooltip_strum_pattern = "라이브러리에서 스트러밍 패턴을 선택합니다.",
  
  -- NEW: Arp Euclidean
  arp_euclidean_enable_checkbox = "유클리드 리듬 사용",
  arp_euclidean_steps_label = "단계 수",
  arp_euclidean_hits_label = "타격 수",
  
  rhythm_section_title = "리듬 적용기",
  rhythm_pattern_label = "리듬 패턴",
  rhythm_apply_button = "리듬 적용",
  tooltip_rhythm_apply = "선택한 리듬 패턴을 코드에 적용합니다.",
  undo_rhythm_button = "리듬 취소",

  -- Drums Tab
  drum_pattern_label = "드럼 패턴",
  drum_generate_button = "드럼 생성",
  tooltip_drum_generate = "항목 전체 길이에 대한 드럼 비트를 생성합니다.\n이전 드럼 음표는 삭제됩니다.",
  drum_generate_fill_button = "필인 생성",
  tooltip_drum_generate_fill = "항목의 마지막 마디에 드럼 필인을 생성합니다.",
  drum_generate_variation_button = "변형 생성",
  tooltip_drum_generate_variation = "현재 드럼 패턴에서 킥/하이햇 음표를 무작위로 추가/제거합니다.",
  drum_error_no_chords = "먼저 코드를 생성하거나 항목에 MIDI 음표가 있어야 합니다.",
  
  -- NEW: Euclidean Sequencer Section
  euclidean_section_title = "유클리드 시퀀서",
  euclidean_instrument_label = "악기",
  euclidean_steps_label = "단계 (16분음표)",
  euclidean_hits_label = "타격 수 (Hits)",
  euclidean_rotation_label = "회전 (Rotation)",
  euclidean_generate_button = "레이어 생성",
  tooltip_euclidean_generate = "유클리드 알고리즘을 사용하여 선택한 악기의 리듬 레이어를 생성합니다.\n이 악기의 기존 음표만 대체합니다.",

  -- Arranger Tab
  arranger_section_title = "프로젝트 편곡기",
  arranger_sync_button = "프로젝트 리전 동기화",
  arranger_sync_tooltip = "현재 Reaper 프로젝트의 모든 리전을 읽어 아래 목록에 표시합니다.",
  arranger_structure_title = "곡 구조 (Regions)",
  arranger_col_id = "ID",
  arranger_col_name = "이름",
  arranger_col_energy = "에너지",
  arranger_col_pos = "시작",
  arranger_col_len = "길이",
  arranger_col_actions = "동작",
  arranger_action_glue = "접착 (Glue)",
  arranger_btn_glue_all = "모든 리전 결합",
  arranger_info_text = "REAPER의 리전(Region)을 사용하여 곡의 섹션(Verse, Chorus 등)을 정의하십시오.",
  arranger_no_regions = "프로젝트에서 리전을 찾을 수 없습니다.",
  
  arranger_pool_title = "패턴 풀",
  arranger_save_button = "항목을 패턴으로 저장",
  arranger_rename_button = "이름 바꾸기",
  arranger_delete_button = "삭제",
  arranger_add_button = "추가",
  arranger_move_up_button = "위로",
  arranger_move_down_button = "아래로",
  arranger_remove_button = "제거",
  arranger_output_track_label = "출력 트랙 이름",
  arranger_regions_checkbox = "섹션별로 리전 생성",
  arranger_generate_button = "편곡 생성",
  arranger_popup_savename_title = "새 패턴 저장",
  arranger_popup_savename_prompt = "새 패턴의 이름을 입력하십시오:",
  arranger_popup_renamename_title = "패턴 이름 바꾸기",
  arranger_popup_rename_prompt = "새 이름을 입력하십시오:",
  arranger_popup_delete_title = "삭제 확인",
  arranger_popup_delete_prompt = "'%s' 패턴을 삭제하시겠습니까?",
  arranger_popup_save_confirm = "저장",
  arranger_popup_rename_confirm = "이름 바꾸기",
  arranger_popup_delete_confirm = "삭제",
  arranger_popup_cancel = "취소",
  arranger_error_empty_name = "오류: 패턴 이름은 비워 둘 수 없습니다.",
  arranger_error_no_item_selected = "오류: 저장할 MIDI 항목을 하나 이상 선택하십시오.",
  arranger_error_empty_structure = "오류: 곡 구조가 비어 있습니다. 하나 이상의 패턴을 추가하십시오.",
  arranger_undo_generate = "편곡 생성",

  -- NEW: Song Architect
  architect_section_title = "송 아키텍트 (구조)",
  architect_template_label = "스타일 템플릿",
  architect_btn_structure = "구조 생성 (Regions)",
  architect_btn_full_song = "전체 곡 생성",
  architect_clear_checkbox = "기존 리전 삭제",
  architect_clear_tracks_checkbox = "기존 트랙 삭제",
  architect_use_existing_chords_checkbox = "기존 코드 사용",
  architect_auto_mixing_checkbox = "자동 믹싱 (볼륨)",
  architect_msg_beta = "'전체 곡 생성' 기능은 v3.2에서 제공될 예정입니다!\n지금은 '구조 생성'을 사용하여 타임라인 뼈대를 잡으세요.",

  -- Settings Tab
  midi_channel_section_title = "MIDI 채널 할당",
  channel_chord_label = "코드 채널",
  channel_bass_label = "베이스 채널",
  channel_melody_label = "멜로디 채널",
  counter_melody_channel_info = "대선율은 채널 %d (멜로디 채널 + 1)에 생성됩니다.",
  channel_info_text = "드럼은 항상 10번 채널입니다.",
  chord_source_section_title = "코드 소스",
  use_chord_track_checkbox = "특정 트랙에서 코드 읽기",
  tooltip_use_chord_track = "활성화하면 크리에이티브 도구가 선택한 항목 대신 아래에 지정된 트랙에서 하모니를 가져옵니다.",
  chord_track_name_label = "코드 트랙 이름",

  -- NEW: Drum Map Section
  drum_map_section_title = "드럼 맵 편집기",
  drum_map_info_text = "각 드럼 파트의 MIDI 노트를 편집합니다 (0-127).",
  drum_map_BassDrum = "베이스 드럼",
  drum_map_SnareStick = "스네어 (림샷)",
  drum_map_SnareHit = "스네어",
  drum_map_Snare_Clap = "스네어/박수",
  drum_map_SnareEdge = "스네어 (림)",
  drum_map_Tom1 = "탐 1 (저음 플로어)",
  drum_map_HiHatClosed = "하이햇 (닫힘)",
  drum_map_Tom2 = "탐 2 (고음 플로어)",
  drum_map_HiHatPedal = "하이햇 페달",
  drum_map_Tom3 = "탐 3 (저음)",
  drum_map_HiHatOpen = "하이햇 (열림)",
  drum_map_MidTom = "탐 4 (중저음)",
  drum_map_Crash = "크래시 1",
  drum_map_HighTom = "탐 5 (고음)",
  drum_map_RideCrash = "라이드 1",
  drum_map_RideBell = "라이드 벨",
  drum_map_Tambourine = "탬버린",
  drum_map_Crash2 = "크래시 2",
  drum_map_OpenHiConga = "콩가 (오픈 하이)",
  drum_map_LowConga = "콩가 (로우)",
  drum_map_Claves = "클라베스",

  -- NEW: Seed System
  seed_label = "시드 (Seed)",
  seed_lock_tooltip = "현재 시드를 잠가서 결과를 재현합니다.",
  seed_new_tooltip = "새로운 무작위 시드를 생성합니다.",

  -- Other UI
  donate_button = "기부",
  feedback_generated = "생성됨: %s %s",
  melody_error_no_chords = "코드를 찾을 수 없습니다. 설정 탭에서 '특정 트랙에서 코드 읽기'를 활성화하십시오.",
  melody_error_no_main_melody = "오류: 대선율의 기반이 될 주선율(멜로디 채널)을 찾을 수 없습니다.",
  melody_error_no_melody_to_mutate = "오류: 멜로디 채널에서 변형할 멜로디 음표를 찾을 수 없습니다.",
  bass_error_no_chords = "코드를 찾을 수 없습니다. 설정 탭에서 '특정 트랙에서 코드 읽기'를 활성화하십시오.",
  arp_error_no_chords = "항목(또는 코드 트랙)에서 아르페지오/스트럼을 적용할 코드를 찾을 수 없습니다.",
  rhythm_error_no_chords_found = "오류: 리듬을 적용할 코드를 항목에서 찾을 수 없습니다.",
  add_note_error_no_notes = "오류: 음표를 찾을 수 없습니다. 새 음표를 추가할 수 없습니다.\n",
  add_note_error_no_scale = "오류: 적절한 스케일을 감지할 수 없습니다. 새 음표를 추가할 수 없습니다。\n",
  add_note_error_no_chords = "오류: 코드를 찾을 수 없습니다. 새 음표를 추가할 수 없습니다.\n",
  error_chord_track_not_found = "오류: '%s'라는 이름의 트랙을 찾을 수 없습니다.",
  error_no_chords_on_track = "오류: 선택한 항목의 시간 범위 내에서 '%s' 트랙에 MIDI 코드를 찾을 수 없습니다.",
  error_item_not_midi_or_empty = "오류: 선택한 항목에 MIDI 음표가 있거나 '코드 트랙에서 읽기'가 활성화되어 있어야 합니다.",
  error_no_item_selected_for_action = "오류: MIDI 항목이 선택되지 않았습니다. '%s' 작업을 수행하기 전에 항목을 선택하십시오.",
  error_item_not_midi_for_action = "오류: 선택한 항목이 MIDI가 아닙니다. '%s' 작업을 위해 유효한 MIDI 항목을 선택하십시오。",
  
  -- NEW: Custom Menu Keys
  custom_menu_button_tooltip = "사용자 정의 메뉴 열기",
  custom_menu_popup_title = "사용자 정의 메뉴 구성",
  custom_menu_popup_info = "메뉴 관리 (드래그 앤 드롭으로 순서 변경)",
  custom_menu_add_to_root = "루트에 추가",
  custom_menu_target_info = "(트리에서 하위 메뉴를 클릭하여 대상으로 선택)",
  custom_menu_add_new_item_title = "새 항목 추가",
  custom_menu_item_type_label = "유형",
  custom_menu_item_type_action = "액션",
  custom_menu_item_type_submenu = "하위 메뉴",
  custom_menu_item_type_separator = "구분선",
  custom_menu_display_name_label = "표시 이름",
  custom_menu_command_id_label = "명령 ID / 스크립트 ID",
  custom_menu_command_id_tooltip = "액션 ID (예: 40001) 또는 스크립트/확장 ID (예: _RS123abc...)를 입력하십시오.",
  custom_menu_add_button = "항목 추가",
  custom_menu_close_button = "닫기",
  custom_menu_empty = "(메뉴가 비어 있습니다)",
  custom_menu_configure_button = "메뉴 구성...",
  custom_menu_delete_button = "삭제",
  custom_menu_dnd_moving = "이동 중: %s",
  custom_menu_dnd_action_label = " (액션)",
  custom_menu_dnd_submenu_label = " (하위 메뉴)",
  custom_menu_dnd_separator_label = "--- 구분 기호 ---",
  
  -- NEW: Header Buttons
  smart_presets_button = "스마트 프리셋",
  analyze_chords_button = "코드 분석",

  -- NEW: Preset Browser Keys
  preset_browser_title = "스마트 프리셋 브라우저",
  preset_factory_vibes = "팩토리 프리셋",
  preset_user_presets = "사용자 프리셋",
  preset_save_vibe = "현재 설정 저장",
  preset_name_label = "이름:",
  preset_save_button = "사용자 프리셋 저장",
  preset_saved_title = "저장됨!",
  preset_saved_msg = "프리셋이 성공적으로 저장되었습니다.",
  preset_tip_delete = "팁: 사용자 프리셋을 우클릭하여 삭제할 수 있습니다.",
  preset_delete_menu = "프리셋 삭제",
  preset_close_button = "닫기",

  -- NEW: Expression Engine
  expression_section_title = "다이내믹 표현 엔진 (Dynamic Expression)",
  expression_dynamics_label = "강약 범위 (%)",
  expression_follow_pitch_checkbox = "피치 추적 (Swell)",
  expression_breath_checkbox = "숨쉬기 (프레이즈 끝 감소)",
  expression_legato_label = "레가토 겹침 (ms)",
  expression_smart_pedal_checkbox = "스마트 서스테인 페달",
  expression_apply_button = "표현 적용",
  undo_expression_button = "표현 취소",
  tooltip_expression_dynamics = "CC1/CC11 모듈레이션의 강도 범위를 조절합니다.",
  tooltip_expression_breath = "프레이즈 끝에서 자동으로 표현을 줄여 숨쉬는 느낌을 줍니다.",
}

return languages