-- ChordGun Help Window (separate context)
-- This runs in its own gfx window without interfering with main script
-- @noindex
--
-- Check if already running - prevent multiple instances
local isRunning = reaper.GetExtState("TK_ChordGun_Help", "running")
local lastHeartbeat = tonumber(reaper.GetExtState("TK_ChordGun_Help", "heartbeat")) or 0
if isRunning == "1" and (reaper.time_precise() - lastHeartbeat) < 1.5 then
	return  -- Exit silently if already open AND alive
end

-- Mark as running
reaper.SetExtState("TK_ChordGun_Help", "running", "1", false)
reaper.SetExtState("TK_ChordGun_Help", "heartbeat", tostring(reaper.time_precise()), false)

-- Cleanup on exit
local function cleanup()
	local dockState, posX, posY = gfx.dock(-1, 0, 0, 0, 0)
	reaper.SetExtState("TK_ChordGun_Help", "windowX", tostring(posX), true)
	reaper.SetExtState("TK_ChordGun_Help", "windowY", tostring(posY), true)
	reaper.SetExtState("TK_ChordGun_Help", "closed", "1", false)  -- Signal main script
	reaper.SetExtState("TK_ChordGun_Help", "running", "0", false)  -- Mark as not running
end
reaper.atexit(cleanup)

-- Tab system
local tabs = {"Getting Started", "Scale System", "Scale Reference", "Chord Controls", "Progression", "Advanced", "About"}
local activeTab = 1
local tabHeight = 30
local scrollOffset = 0
local maxScroll = 0

-- Help content organized by tabs
local helpContent = {
	-- Tab 1: Getting Started
	{
		"CHORDGUN (TK MOD) v2.5.2",
		"Quick Start Guide",
		"",
		"=== NEW IN v2.5.2 ===",
		"• Default Velocity: \"Vel:\" button in top frame (next to Oct:/Inv:)",
		"  Left-click cycles presets, right-click opens menu",
		"  (Follow MIDI Editor / 16 / 32 / 48 / 64 / 80 / 96 / 112 / 127 / Custom)",
		"• Per-Slot Velocity: \"V\" button on left side of each progression slot",
		"  opens a velocity panel with theme-styled slider (1-127)",
		"  overriding the global Vel: for that slot",
		"  Click \"x\" in the panel to reset to follow global",
		"  Persists with progression presets",
		"• Drag & Drop: Chord buttons can be dragged onto progression slots",
		"• Persistence: Always on Top and Tooltips toggles remembered between sessions",
		"• UI: Removed redundant \"Scale:\" label to free space for Vel: button",
		"",
		"=== NEW IN v2.5.1 ===",
		"• Absolute Chord Storage: Progressions store chords by root + type",
		"• Filter-Independent Playback: Progressions play exact chords regardless of scale/filter changes",
		"• Backwards Compatible: Old preset files still work with fallback",
		"• Chord Button Highlighting: Correct button highlights during playback",
		"• Out-of-Scale Display: Chord display shows correct color for out-of-scale chords",
		"• Chord Name Display: Extended chords (Amaj#11) display correctly",
		"• Hidden Chord Indicator: Orange overlay when chord not visible in filter",
		"• Piano Visualization Fix: Keys clear properly when releasing buttons",
		"",
		"=== NEW IN v2.5.0 ===",
		"• UI Reorganization: Lead button moved to bottom row",
		"• Circle Icon: Circle of Fifths accessible via icon in chord display",
		"• Chord Style Dropdown: Simple, Standard, Extended, Ambient, Jazz, Pop, Neo-Soul",
		"• 'All' Checkbox: Toggle to show out-of-scale chords",
		"• Track Name: Shows in chord display (truncated to 10 chars)",
		"",
		"=== NEW IN v2.4.1 ===",
		"• MIDI Trigger Cascade Fix: Chord notes no longer re-trigger other chords",
		"• Virtual MIDI Detection: Cross-platform device detection",
		"• Channel 16 Bypass: Triggered chords play on channel 16",
		"• Piano Trigger Visualization: Trigger notes shown in separate color",
		"• Split Key Display: Keys show both trigger and chord colors",
		"• 6 Color Themes: Dark, Light, Color, Neon, Ocean, Mono",
		"",
		"=== NEW IN v2.4.0 ===",
		"• Custom MIDI Trigger Mapping: Assign any MIDI note to any chord",
		"• Column Mode: Trigger scale degree columns with single MIDI notes",
		"• Built-in Preset: 'White Keys (C2-B2)' for quick Column Mode setup",
		"• Preset System: Save/Load trigger mappings to ChordMaps folder",
		"• Visual Indicators: Yellow squares for mapped triggers",
		"• Preset Display: Current preset name shown in chord display",
		"",
		"=== NEW IN v2.3.5 ===",
		"• Progression Templates: 70+ preset progressions (Right-click Load)",
		"• Genre categories: Pop/Rock, Jazz, Blues, Classical, Modal, EDM, World",
		"• Mode-aware: Templates auto-adapt to current scale",
		"",
		"=== WHAT IS CHORDGUN? ===",
		"ChordGun is an intelligent chord generator and scale reference tool.",
		"It helps you compose with:",
		"• 88 scales from 9 music systems (Diatonic, Jazz, World, etc.)",
		"• Support for 5 to 10 note scales (including Messiaen modes)",
		"• Scale-aware chord suggestions with Roman numeral notation",
		"• Real-time chord recognition (including Power Chords/C5)",
		"• Interactive Circle of Fifths with Chromatic, Score & Guitar Views",
		"• Melody Generator for instant musical ideas",
		"• Arpeggiator for rhythmic chord patterns",
		"• Automatic Voice Leading for smooth transitions",
		"• Chord progression builder with playback",
		"",
		"=== BASIC WORKFLOW ===",
		"1. Select Scale System (Diatonic, Jazz, World Music, etc.)",
		"2. Choose specific scale (Major, Minor, Dorian, Hijaz, etc.)",
		"3. Click chord buttons (I, ii, iii, IV, V, vi, vii°) to preview",
		"4. Shift+Click to insert chords into your REAPER project",
		"5. Build progressions with Alt+Click to add chords to slots",
		"",
		"=== CHORD STYLE FILTER (NEW!) ===",
		"Control which chords are visible:",
		"• Simple: Basic triads only (maj, min, dim, aug, sus)",
		"• Standard: Triads + 7th chords (Default)",
		"• Extended: All chord types including 9th, 11th, 13th",
		"• Ambient: Atmospheric chords (sus2, add9, power)",
		"• Jazz: Complex chords (maj7, min7, dom7, altered)",
		"• Pop: Common pop/rock chords",
		"• Neo-Soul: R&B/Gospel chord vocabulary",
		"• 'All' checkbox: Also show out-of-scale chords",
		"",
		"=== TOOLTIPS ===",
		"• Tooltip checkbox (☑/☐ next to LOAD button)",
		"  - Toggle on to see detailed help for each button",
		"  - Hover over any control to see available actions",
		"",
		"=== MAIN CONTROLS ===",
		"• HOLD: Keep notes playing after mouse release",
		"• KILL: Stop all playing notes immediately (Spacebar)", 
		"• LEAD: Automatic voice leading for smooth transitions",
		"• DROP: Select Drop 2, Drop 3, or Bass voicings",
		"• STRUM: Strum notes with adjustable delay",
		"• ARP: Arpeggiate notes (Up, Down, Random, etc.)",
		"• MELODY: Generate random melodies based on scale",
		"• Note Length: Set duration (Selection, 1/4, 1/8, etc.)",
		"• Circle button: Open Circle of Fifths / Score / Guitar views",
		"• DOCK/UNDOCK: Attach window to REAPER docker",
		"",
		"TIP: Start with tooltips enabled to discover all features!",
	},
	
	-- Tab 2: Scale System
	{
		"SCALE SYSTEM",
		"88 Scales Across 9 Musical Traditions",
		"",
		"=== NEW IN v2.0: TWO-LEVEL SCALE SELECTION ===",
		"• Scale System dropdown (Level 1):",
		"  Choose music tradition: Diatonic, Pentatonic, Messiaen,",
		"  Harmonic Minor Modes, Melodic Minor Modes, Jazz,",
		"  World Music, Blues & Soul, Rock & Metal",
		"",
		"• Scale Type dropdown (Level 2):",
		"  Select specific scale within chosen system",
		"  Updates dynamically based on system selection",
		"",
		"• Tonic Note dropdown:",
		"  Choose root note (C, C#, D, Eb, E, F, etc.)",
		"",
		"=== EDUCATIONAL TOOLTIPS ===",
		"Hover over scale dropdown (with tooltips enabled) to see:",
		"• Scale type and note count (Pentatonic, Heptatonic, etc.)",
		"• Musical character and mood description",
		"• Interval pattern in semitones",
		"• Historical context and usage examples",
		"• Famous composers/artists who use the scale",
		"",
		"=== SCALE SYSTEMS OVERVIEW ===",
		"",
		"DIATONIC (9 scales) - Western classical and pop",
		"Major, Natural Minor, Church modes",
		"(Harmonic/Melodic Minor moved to their own categories)",
		"",
		"HARMONIC MINOR MODES (7 scales)",
		"Harmonic Minor, Phrygian Dominant, Locrian #6, etc.",
		"",
		"MELODIC MINOR MODES (7 scales)",
		"Melodic Minor, Lydian Dominant, Altered Scale, etc.",
		"",
		"PENTATONIC (6 scales) - 5-note scales",
		"Major/Minor Pentatonic, Blues Scale, Egyptian,",
		"Japanese (Hirajoshi), Hirajoshi variant",
		"",
		"MESSIAEN (32 modes) - Symmetrical limited transposition",
		"Mode 1: Whole Tone (6 notes)",
		"Mode 2: Octatonic/Diminished (8 notes)",
		"Mode 3: Nonatonic (9 notes)",
		"Mode 7: Decatonic (10 notes)",
		"Named after French composer Olivier Messiaen",
		"",
		"JAZZ (10 scales) - Bebop and modern jazz",
		"Bebop scales (Dominant, Major, Minor, Dorian)",
		"Altered Scale, Lydian Dominant, Harmonic Major,",
		"Melodic Minor, Diminished scales",
		"",
		"WORLD MUSIC (12 scales) - Global traditions",
		"Arabic/Middle Eastern: Hijaz, Persian, Double Harmonic",
		"Japanese: In Sen, Iwato, Hirajoshi",
		"Indian: Bhairav Raga, Kafi Raga",
		"European: Hungarian Minor, Spanish 8-Tone, Enigmatic",
		"",
		"BLUES & SOUL (8 scales) - American roots music",
		"Blues variants (Major, Minor, Classic)",
		"Gospel scales (Major, Minor)",
		"Mixo-Blues, Dominant Blues, Soul scale",
		"",
		"ROCK & METAL (8 scales) - Heavy and progressive",
		"Harmonic Minor, Phrygian Dominant",
		"Neapolitan Minor/Major, Hungarian Major",
		"Super Locrian, Lydian #2, Aeolian b5",
		"",
		"=== NAVIGATION SHORTCUTS ===",
		"• Ctrl + ,/.: Navigate tonic note",
		"• Ctrl + </>: Navigate scale type within system",
		"",
		"=== SCALE FILTER/REMAP MODES ===",
		"• OFF/FILTER/REMAP button:",
		"  - Click: Cycle through modes",
		"  - OFF: No filtering",
		"  - FILTER: Block notes outside scale",
		"  - REMAP: Map white keys to scale notes",
		"",
		"• Setup button:",
		"  Auto-add TK Scale Filter JSFX to track Input FX",
		"  Required for Filter/Remap to work with live MIDI",
		"",
		"• Remap Mode Details:",
		"  White keys map to scale degrees (C→1, D→2, etc.)",
		"  Black keys still work for chord button shortcuts",
		"  Piano shows remap arrows (e.g., 'E→Eb' in C Minor)",
		"",
	},
	
	-- Tab 3: Scale Reference
	{
		"SCALE REFERENCE",
		"Complete Encyclopedia of All 88 Scales",
		"",
		"=== DIATONIC SCALES (9) ===",
		"Western classical music foundation - 7 notes per octave",
		"",
		"1. MAJOR (Ionian)",
		"   Intervals: 2-2-1-2-2-2-1",
		"   Character: Bright, happy, uplifting",
		"   Use: Pop, classical, most Western music",
		"   Example: C Major = C-D-E-F-G-A-B",
		"",
		"2. NATURAL MINOR (Aeolian)",
		"   Intervals: 2-1-2-2-1-2-2",
		"   Character: Dark, melancholic, serious",
		"   Use: Rock, metal, emotional ballads",
		"   Example: A Natural Minor = A-B-C-D-E-F-G",
		"",
		"3. DORIAN",
		"   Intervals: 2-1-2-2-2-1-2",
		"   Character: Minor with bright 6th, jazzy",
		"   Use: Jazz, funk, Celtic music",
		"   Example: D Dorian = D-E-F-G-A-B-C",
		"",
		"4. PHRYGIAN",
		"   Intervals: 1-2-2-2-1-2-2",
		"   Character: Spanish, dark, exotic",
		"   Use: Flamenco, metal, Middle Eastern",
		"   Example: E Phrygian = E-F-G-A-B-C-D",
		"",
		"5. LYDIAN",
		"   Intervals: 2-2-2-1-2-2-1",
		"   Character: Dreamy, floating, #4",
		"   Use: Film scores, jazz, progressive",
		"   Example: F Lydian = F-G-A-B-C-D-E",
		"",
		"6. MIXOLYDIAN",
		"   Intervals: 2-2-1-2-2-1-2",
		"   Character: Major with b7, bluesy",
		"   Use: Blues, rock, folk, Celtic",
		"   Example: G Mixolydian = G-A-B-C-D-E-F",
		"",
		"7. LOCRIAN",
		"   Intervals: 1-2-2-1-2-2-2",
		"   Character: Unstable, diminished, dark",
		"   Use: Jazz, metal, experimental",
		"   Example: B Locrian = B-C-D-E-F-G-A",
		"",
		"8. HARMONIC MAJOR",
		"   Intervals: 2-2-1-2-1-3-1",
		"   Character: Major with b6, exotic",
		"   Use: Jazz, metal, film scores",
		"   Example: C Harmonic Major = C-D-E-F-G-Ab-B",
		"",
		"9. DOUBLE HARMONIC",
		"   Intervals: 1-3-1-2-1-3-1",
		"   Character: Byzantine, Arabic, dramatic",
		"   Use: Middle Eastern, progressive metal",
		"   Example: C Double Harmonic = C-Db-E-F-G-Ab-B",
		"",
		"=== HARMONIC MINOR MODES (7) ===",
		"Modes derived from the Harmonic Minor scale",
		"",
		"1. HARMONIC MINOR (Aeolian #7)",
		"   Intervals: 2-1-2-2-1-3-1",
		"   Character: Exotic, classical, dramatic",
		"   Use: Classical, neoclassical metal, flamenco",
		"",
		"2. LOCRIAN #6",
		"   Intervals: 1-2-2-1-3-1-2",
		"   Character: Dark, diminished quality",
		"   Use: Jazz, modern composition",
		"",
		"3. IONIAN #5 (Ionian Augmented)",
		"   Intervals: 2-2-1-3-1-2-1",
		"   Character: Dreamy, unsettled major",
		"   Use: Film scores, jazz",
		"",
		"4. DORIAN #4 (Dorian #11)",
		"   Intervals: 2-1-3-1-2-1-2",
		"   Character: Bluesy minor with sharp 4",
		"   Use: Folk, fusion",
		"",
		"5. PHRYGIAN DOMINANT (Phrygian Major)",
		"   Intervals: 1-3-1-2-1-2-2",
		"   Character: Spanish, Flamenco, Metal",
		"   Use: Metal, flamenco, Middle Eastern",
		"",
		"6. LYDIAN #2",
		"   Intervals: 3-1-2-1-2-2-1",
		"   Character: Bright, angular, modern",
		"   Use: Progressive metal, math rock",
		"",
		"7. SUPER LOCRIAN bb7 (Altered bb7)",
		"   Intervals: 1-2-1-2-2-1-3",
		"   Character: Diminished, very dissonant",
		"   Use: Jazz, diminished chords",
		"",
		"=== MELODIC MINOR MODES (7) ===",
		"Modes derived from the Melodic Minor scale",
		"",
		"1. MELODIC MINOR (Jazz Minor)",
		"   Intervals: 2-1-2-2-2-2-1",
		"   Character: Smooth ascending, jazz foundation",
		"   Use: Jazz, fusion, modern composition",
		"",
		"2. DORIAN b2 (Phrygian #6)",
		"   Intervals: 1-2-2-2-2-1-2",
		"   Character: Dark minor with natural 6",
		"   Use: Jazz, modal interchange",
		"",
		"3. LYDIAN AUGMENTED (Lydian #5)",
		"   Intervals: 2-2-2-2-1-2-1",
		"   Character: Dreamy, whole-tone feel",
		"   Use: Modern jazz, film scores",
		"",
		"4. LYDIAN DOMINANT (Lydian b7)",
		"   Intervals: 2-2-2-1-2-1-2",
		"   Character: Acoustic scale, bright dominant",
		"   Use: Jazz, Bartók, Debussy",
		"",
		"5. MIXOLYDIAN b6 (Hindu)",
		"   Intervals: 2-2-1-2-1-2-2",
		"   Character: Melodic major/minor hybrid",
		"   Use: Jazz, Indian fusion",
		"",
		"6. LOCRIAN #2 (Aeolian b5)",
		"   Intervals: 2-1-2-1-2-2-2",
		"   Character: Dark, jazzy minor",
		"   Use: Half-diminished chords",
		"",
		"7. SUPER LOCRIAN (Altered Scale)",
		"   Intervals: 1-2-1-2-2-2-2",
		"   Character: Dominant altered tensions",
		"   Use: Jazz dominant chords",
		"",
		"=== PENTATONIC SCALES (6) ===",
		"5-note scales - universal across cultures",
		"",
		"1. MAJOR PENTATONIC",
		"   Intervals: 2-2-3-2-3",
		"   Character: Bright, happy, folk-like",
		"   Use: Folk, country, rock solos",
		"   Example: C Major Pent = C-D-E-G-A",
		"",
		"2. MINOR PENTATONIC",
		"   Intervals: 3-2-2-3-2",
		"   Character: Bluesy, rock, versatile",
		"   Use: Rock, blues, metal solos",
		"   Example: A Minor Pent = A-C-D-E-G",
		"",
		"3. BLUES SCALE (Hexatonic - 6 notes)",
		"   Intervals: 3-2-1-1-3-2",
		"   Character: Classic blues with blue note",
		"   Use: Blues, rock, jazz foundation",
		"   Example: A Blues = A-C-D-Eb-E-G",
		"",
		"4. EGYPTIAN",
		"   Intervals: 2-3-2-3-2",
		"   Character: Exotic, ancient, mysterious",
		"   Use: World music, film scores",
		"   Example: C Egyptian = C-D-F-G-Bb",
		"",
		"5. JAPANESE (IN SEN)",
		"   Intervals: 1-4-2-3-2",
		"   Character: Meditative, contemplative",
		"   Use: Traditional Japanese, Zen",
		"   Example: C In Sen = C-Db-F-G-Bb",
		"",
		"6. HIRAJOSHI",
		"   Intervals: 2-1-4-1-4",
		"   Character: Japanese, serene",
		"   Use: Tranquil, peaceful",
		"   Example: C Hirajoshi = C-D-Eb-G-Ab",
		"",
		"=== MESSIAEN MODES (32) ===",
		"Symmetrical modes of limited transposition",
		"Named after French composer Olivier Messiaen",
		"",
		"MODE 1 - WHOLE TONE (1 transposition)",
		"• Mode 1: 2-2-2-2-2-2 (6 notes)",
		"  Dreamy, floating, ambiguous | Debussy favorite",
		"",
		"MODE 2 - OCTATONIC (3 transpositions)",
		"• Mode 2.1: 1-2-1-2-1-2-1-2 (8 notes, half-whole)",
		"• Mode 2.2: 2-1-2-1-2-1-2-1 (8 notes, whole-half)",
		"• Mode 2.3: 1-2-1-2-1-2-1-2 (8 notes, 3rd transposition)",
		"  Jazz/classical favorite | Rich chords",
		"",
		"MODE 3 - NONATONIC (4 transpositions)",
		"• Mode 3.1-3.4: 2-1-1 / 1-1-2 / 1-2-1 patterns (9 notes)",
		"  Dense, chromatic, colorful",
		"  Used in Messiaen's 'Quartet for the End of Time'",
		"",
		"MODE 4 - OCTATONIC (6 transpositions)",
		"• Mode 4.1-4.6: 1-1-3-1 patterns (8 notes)",
		"  Exotic, Eastern flavor",
		"  Mysterious, otherworldly sounds",
		"",
		"MODE 5 - HEXATONIC (6 transpositions)",
		"• Mode 5.1-5.6: 1-4-1 patterns (6 notes)",
		"  Wide intervals, sparse, spacious",
		"  Ethereal, floating textures",
		"",
		"MODE 6 - OCTATONIC (6 transpositions)",
		"• Mode 6.1-6.6: 2-2-1-1 patterns (8 notes)",
		"  Balanced, versatile",
		"  Blends whole tone and chromatic",
		"",
		"MODE 7 - DECATONIC (6 transpositions)",
		"• Mode 7.1-7.6: 1-1-1-2-1 patterns (10 notes)",
		"  Most chromatic, maximum color",
		"  Messiaen's most complex mode",
		"",
		"=== JAZZ SCALES (5) ===",
		"Bebop and modern jazz harmony",
		"",
		"1. BEBOP DOMINANT",
		"   Intervals: 2-2-1-2-2-1-1-1 (8 notes)",
		"   Character: Classic bebop sound",
		"   Use: Dominant 7th chord lines",
		"   Mixolydian + major 7th passing tone",
		"",
		"2. BEBOP MAJOR",
		"   Intervals: 2-2-1-2-1-1-2-1 (8 notes)",
		"   Character: Major with chromatic",
		"   Use: Smooth bebop melodies",
		"   Major scale + #5 passing tone",
		"",
		"3. BEBOP MINOR",
		"   Intervals: 2-1-2-2-1-1-2-1 (8 notes)",
		"   Character: Minor with chromatic",
		"   Use: Bebop improvisation",
		"   Dorian + major 3rd passing tone",
		"",
		"4. BEBOP DORIAN",
		"   Intervals: 2-1-2-2-2-1-1-2 (8 notes)",
		"   Character: Dorian with passing tone",
		"   Use: Miles Davis, John Coltrane favorite",
		"",
		"5. HARMONIC MAJOR",
		"   Intervals: 2-2-1-2-1-3-1 (7 notes)",
		"   Character: Major with b6",
		"   Use: Jazz and metal, exotic sound",
		"",
		"(See Melodic Minor Modes for Altered, Lydian Dom, etc.)",
		"",
		"=== WORLD MUSIC SCALES (11) ===",
		"Global musical traditions",
		"",
		"ARABIC/MIDDLE EASTERN:",
		"",
		"1. HIJAZ",
		"   Intervals: 1-3-1-2-1-2-2",
		"   Character: Arabic Maqam, dramatic",
		"   Use: Arabic, Turkish, Greek, Klezmer",
		"   Augmented 2nd interval creates tension",
		"",
		"2. DOUBLE HARMONIC",
		"   Intervals: 1-3-1-2-1-3-1",
		"   Character: Byzantine/Arabic, extreme exotic",
		"   Use: Middle Eastern, Indian, prog metal",
		"   Two augmented 2nds",
		"",
		"3. PERSIAN",
		"   Intervals: 1-3-1-2-1-3-1",
		"   Character: Persian/Iranian classical",
		"   Use: Traditional Persian and Sufi music",
		"   Similar to Double Harmonic",
		"",
		"JAPANESE:",
		"",
		"4. HIRAJOSHI",
		"   Intervals: 2-1-4-1-4 (5 notes)",
		"   Character: Traditional court music",
		"   Use: Koto, shakuhachi, ambient",
		"   Spacious, contemplative",
		"",
		"5. IN SEN",
		"   Intervals: 1-4-2-1-4 (5 notes)",
		"   Character: Shakuhachi scale",
		"   Use: Zen Buddhist meditation",
		"   Minor pentatonic variant, melancholic",
		"",
		"6. IWATO",
		"   Intervals: 1-4-1-4-2 (5 notes)",
		"   Character: Dark, mysterious",
		"   Use: Dramatic and suspenseful scenes",
		"   Ancient court music",
		"",
		"INDIAN:",
		"",
		"7. BHAIRAV (Raga)",
		"   Intervals: 1-3-1-2-1-3-2",
		"   Character: Dawn raga, peaceful yet serious",
		"   Use: Classical Indian, meditative",
		"   North Indian tradition",
		"",
		"8. KAFI (Raga)",
		"   Intervals: 2-2-1-2-2-1-2",
		"   Character: Dorian-like, romantic longing",
		"   Use: Folk and light classical",
		"   Popular in Hindustani music",
		"",
		"EUROPEAN/OTHER:",
		"",
		"9. HUNGARIAN MINOR",
		"   Intervals: 2-1-3-1-1-3-1",
		"   Character: Gypsy/Hungarian, dramatic",
		"   Use: Liszt, Brahms, Eastern European folk",
		"   Minor with raised 4th",
		"",
		"10. SPANISH 8-TONE",
		"   Intervals: 1-2-1-1-2-1-2-2 (8 notes)",
		"   Character: Flamenco composite",
		"   Use: Modern flamenco, fusion guitar",
		"   Combines Phrygian and altered tones",
		"",
		"11. ENIGMATIC",
		"   Intervals: 1-3-2-2-2-1-1",
		"   Character: Verdi's scale, mysterious",
		"   Use: Rare, experimental compositions",
		"   Unusual intervals, Giuseppe Verdi",
		"",
		"=== BLUES & SOUL SCALES (8) ===",
		"American roots music",
		"",
		"1. BLUES SCALE",
		"   Intervals: 3-2-1-1-3-2 (6 notes)",
		"   Character: Classic blues with blue note",
		"   Use: Foundation of blues, rock, jazz",
		"   Minor pentatonic + b5",
		"",
		"2. BLUES MAJOR",
		"   Intervals: 2-1-1-2-2-2-2 (7 notes)",
		"   Character: Major blues flavor",
		"   Use: Country, blues-rock, Southern rock",
		"   Major pentatonic + blue notes",
		"",
		"3. BLUES MINOR",
		"   Intervals: 3-2-1-1-2-3 (6 notes)",
		"   Character: Minor blues variant",
		"   Use: Chicago blues, blues-rock",
		"   Minor pentatonic + major 3rd",
		"",
		"4. MIXO-BLUES",
		"   Intervals: 2-2-1-2-1-1-2-1 (8 notes)",
		"   Character: Jazz-blues hybrid",
		"   Use: Jazz-blues, funk, fusion",
		"   Mixolydian + blue notes (#9, #11)",
		"",
		"5. GOSPEL MINOR",
		"   Intervals: 3-2-1-2-2-2 (6 notes)",
		"   Character: Soulful, churchy, emotional",
		"   Use: Gospel, R&B, soul music",
		"   Minor with raised 6th",
		"",
		"6. GOSPEL MAJOR",
		"   Intervals: 2-2-2-1-1-2-2 (7 notes)",
		"   Character: Uplifting, joyful",
		"   Use: Gospel choir, worship music",
		"   Major with chromatic passing tones",
		"",
		"7. DOMINANT BLUES",
		"   Intervals: 2-2-1-2-2-1-2-2 (8 notes)",
		"   Character: Dominant 7th blues",
		"   Use: Texas blues, rockabilly, swing",
		"   Mixolydian + blue note",
		"",
		"8. SOUL",
		"   Intervals: 2-1-2-2-2-2-1-2 (8 notes)",
		"   Character: Smooth R&B sound",
		"   Use: Motown, 70s soul, neo-soul",
		"   Major + chromatic approach notes",
		"",
		"=== ROCK & METAL SCALES (3) ===",
		"Heavy and progressive music",
		"",
		"1. NEAPOLITAN MINOR",
		"   Intervals: 1-2-2-2-1-3-1",
		"   Character: Dark exotic minor",
		"   Use: Symphonic metal, film scores",
		"   Minor with flattened 2nd",
		"",
		"2. NEAPOLITAN MAJOR",
		"   Intervals: 1-2-2-2-2-2-1",
		"   Character: Bright yet exotic",
		"   Use: Progressive rock/metal, experimental",
		"   Major with flattened 2nd",
		"",
		"3. HUNGARIAN MAJOR",
		"   Intervals: 3-1-2-1-2-1-2",
		"   Character: Exotic major sound",
		"   Use: Gypsy-flavored rock, folk metal",
		"   Lydian with flat 6 and 7",
	},
	
	-- Tab 4: Chord Controls
	{
		"CHORD CONTROLS",
		"Playing and Inserting Chords",
		"",
		"=== CHORD BUTTONS (I - vii°) ===",
		"Roman numerals show scale degree and chord quality:",
		"• Uppercase (I, IV, V) = Major chords",
		"• Lowercase (ii, iii, vi) = Minor chords", 
		"• Diminished (vii°) = Diminished chord",
		"",
		"Button Actions:",
		"• Click: Preview chord (plays notes)",
		"• Shift+Click: Insert chord at edit cursor",
		"• Alt+Click: Add chord to progression slot",
		"• Ctrl+Click: Cycle inversion (root → 1st → 2nd → 3rd)",
		"  Yellow I1/I2/I3 badge appears in top-right of the button",
		"  Cycle resets after 2 seconds of no Ctrl+Click on the same button",
		"• Ctrl+Shift+Click: Insert chord using the current cycle inversion",
		"• Ctrl+Alt+Click: Add chord to slot using the current cycle inversion",
		"• Right Click: Open Context Menu (Generate ii-V-I, Tritone Subs, etc.)",
		"• Hold & drag: Continuous preview",
		"",
		"=== CHORD STYLE FILTER (NEW in v2.5.0) ===",
		"Controls which chords are visible:",
		"• Simple: Basic triads (Major, Minor, Dim, Aug, Sus)",
		"• Standard: Triads + 7th chords (Default)",
		"• Extended: All chords including 9th, 11th, 13th",
		"• Ambient: Atmospheric chords (sus2, add9, power, 5/5)",
		"• Jazz: Complex jazz chords (maj7, min7, altered, extensions)",
		"• Pop: Common pop/rock chord vocabulary",
		"• Neo-Soul: R&B/Gospel chords (min9, 7#9, maj9)",
		"• 'All' Checkbox: Also show out-of-scale chords (greyed out)",
		"",
		"=== PROGRESSION PLAYBACK BEHAVIOR (v2.5.1) ===",
		"Progressions now store chords absolutely:",
		"• Chords are saved by root note + chord type",
		"• Changing scale/filter does NOT change what plays",
		"• Visual feedback during playback:",
		"  - Correct chord button highlights (if visible)",
		"  - Orange overlay when chord not in current filter",
		"  - Out-of-scale chords show in red/orange text",
		"",
		"=== CONTEXT MENU (Right-Click) ===",
		"Right-click any chord button to access:",
		"• Generate Leading Chords:",
		"  - Add ii-V-I: Creates a jazz cadence leading to the clicked chord",
		"  - Add ii-bII-I: Creates a Tritone Substitution cadence",
		"• Insert Options:",
		"  - Insert to MIDI: Writes notes directly to the MIDI item",
		"  - Add to Progression: Appends chords to the progression slots",
		"• Stop All Notes: Quickly silence any playing notes",
		"",
		"=== DROP VOICING BUTTON ===",
		"Toggle button with Menu (Drop 2 / Drop 3 / Bass):",
		"• Drop 2: Moves 2nd highest note down 1 octave (Jazz style)",
		"• Drop 3: Moves 3rd highest note down 1 octave (Open style)",
		"• Bass -1/-2: Adds root note 1 or 2 octaves below",
		"• Combine options for rich, complex voicings",
		"• Right-Click: Clear all voicings",
		"",
		"=== CHORD RECOGNITION ===",
		"Chord Display (center top):",
		"• Shows currently played chord name in real-time",
		"• Works with chord buttons AND external MIDI keyboard",
		"• Color coding:",
		"  - In-scale: Normal text color",
		"  - Out-of-scale: Red/Orange text (theme dependent)",
		"  - Orange overlay: Chord not visible in current filter",
		"• Shows track name (truncated) in top-left",
		"• Shows MIDI trigger preset name (if active)",
		"",
		"Recognized Chord Types:",
		"Major, Minor, Diminished, Augmented, Sus2, Sus4,",
		"Major 7th, Minor 7th, Dominant 7th, Diminished 7th,",
		"Half-diminished (m7b5), Major 9th, Minor 9th,",
		"11th, 13th, 6/9, add9, Power Chords (C5)",
		"",
		"=== CHORD INVERSION ===",
		"Inversion value box (next to octave):",
		"• Click arrows: Preview with new inversion",
		"• Shift+Click arrows: Insert with new inversion",
		"• Cmd/Ctrl + ,/.: Navigate inversions",
		"",
		"Inversions explained:",
		"• 0 = Root position (C-E-G)",
		"• 1 = First inversion (E-G-C)",
		"• 2 = Second inversion (G-C-E)",
		"",
		"=== OCTAVE CONTROL ===",
		"Octave value box:",
		"• Click arrows: Change octave range",
		"• Alt + ,/.: Decrease/increase octave",
		"• Range: -2 to 8 (MIDI octaves)",
		"",
		"=== VELOCITY CONTROL ===",
		"Vel: button (next to Oct:/Inv: in top frame):",
		"• Left-click: Cycle through preset values",
		"  (Follow MIDI Editor / 16 / 32 / 48 / 64 / 80 / 96 / 112 / 127)",
		"• Right-click: Open menu with all presets + Custom...",
		"• \"Edit\" label = following MIDI Editor default velocity",
		"• Custom value: Enter any value 1-127",
		"• Persists between sessions",
		"",
		"Per-Slot Velocity ([V] button on filled progression slot):",
		"• Click V to open panel with theme-styled slider (1-127)",
		"• Slot velocity overrides the global Vel: for preview,",
		"  progression playback and MIDI insert",
		"• \"x\" button: Reset slot to follow global Vel:",
		"• Saved with progression presets",
		"",
		"=== PLAYBACK CONTROLS ===",
		"• HOLD button:",
		"  Toggle hold mode - notes sustain after mouse release",
		"  Useful for auditioning chord progressions",
		"",
		"• KILL button:",
		"  Immediately stop all playing notes",
		"  Also triggered by: SPACE, Middle mouse, Right-click chord",
		"",
		"• LEAD button:",
		"  Toggle Automatic Voice Leading",
		"  - Chooses inversions to minimize finger movement",
		"  - Creates smooth transitions between chords",
		"",
		"• DROP button:",
		"  - Click: Toggle Drop voicing mode",
		"  - Right-Click: Select voicing type menu",
		"",
		"• STRUM button:",
		"  - Click: Toggle strum mode",
		"  - Ctrl+Click: Adjust strum delay (10-500ms)",
		"",
		"• ARP button:",
		"  - Click: Toggle Arpeggiator mode",
		"  - Right-Click: Select Pattern (Up, Down, Up/Down, Random)",
		"  - Ctrl+Click: Set Speed",
		"",
		"• MELODY button:",
		"  - Click: Generate a random melody in current scale",
		"  - Ctrl+Click: Adjust melody settings",
		"",
		"• Note Length dropdown:",
		"  Set duration for inserted notes (1/4, 1/8, 1/16, etc.)",
		"",
	},
	
	-- Tab 4: Progression
	{
		"CHORD PROGRESSION",
		"Building and Playing Progressions",
		"",
		"=== PROGRESSION SLOTS ===",
		"16 slots for building chord sequences",
		"",
		"Slot Actions:",
		"• Click empty slot: Select for chord assignment",
		"• Alt+Click chord button: Add chord to selected slot",
		"• Drag chord button onto slot: Assign chord to slot",
		"• Click filled slot: Preview chord (500ms) and select",
		"• Shift+Click slot: Set as loop endpoint (orange marker)",
		"• [+] button (top-right of filled slot): Edit beats / repeats /",
		"  octave / inversion (per-slot overrides)",
		"• [V] button (top-left of filled slot): Open per-slot velocity",
		"  panel with slider (1-127). \"x\" resets to follow global Vel:",
		"• Ctrl+Click slot: Edit beats and repeats (legacy shortcut)",
		"• Right Click: Clear slot",
		"",
		"=== BEATS AND REPEATS ===",
		"Click the [+] button on a filled slot to adjust:",
		"• Beats: Duration in beats (0.5, 1, 2, 4, or 8)",
		"• Repeats: How many times to play (1-4)",
		"• Octave: Per-slot octave override",
		"• Inversion: Per-slot inversion override",
		"",
		"Example: A slot with 2 beats × 3 repeats = 6 beats total",
		"",
		"=== DEFAULT CHORD LENGTH ===",
		"Right-click the beats column of the [+] panel:",
		"• Default For New Chords: 0.5 / 1 / 2 / 4 (1 bar) / 8 (2 bars)",
		"  Every chord added to an empty slot from then on uses it",
		"  Saved globally, so it survives project and script restarts",
		"• Use This Slot's Length As Default: take it from this slot",
		"• Apply Default Length To All Slots: set every filled slot",
		"  in the current progression to the default in one go",
		"",
		"=== TIGHT TIMING (JSFX ENGINE) ===",
		"Right-click the PLAY button to toggle it on:",
		"• Playback moves to a JSFX that plays the progression",
		"  from the audio thread, on the exact sample",
		"• Adds TK_ChordGun_Sequencer at the top of the selected",
		"  track's normal FX chain (above your instrument)",
		"• Works whether or not the track is record-armed",
		"• Strum and arp no longer freeze the UI between notes",
		"• Off, or no track selected: falls back to the old timing",
		"• Notes played this way are heard, but not recorded --",
		"  use INSERT to write the progression into an item",
		"",
		"=== LOOP ENDPOINT ===",
		"Shift+Click slot to mark loop end:",
		"• Orange marker appears on slot",
		"• Playback loops from slot 1 to marked slot",
		"• Only one endpoint allowed (auto-moves)",
		"• Shift+Click same slot to remove endpoint",
		"",
		"=== PLAYBACK CONTROLS ===",
		"• PLAY: Start progression playback from slot 1",
		"  Loops continuously if endpoint is set",
		"  Plays once through if no endpoint",
		"  Right-Click: Sync Play and Tight Timing",
		"  Button colour: blue = Sync Play, green = Tight Timing,",
		"  teal = both, orange = Tight Timing on but not running",
		"",
		"• STOP: Stop progression playback",
		"  Notes stop immediately",
		"",
		"=== PROGRESSION MANAGEMENT ===",
		"• CLEAR: Remove all chords from slots",
		"  Confirmation required (prevents accidents)",
		"",
		"• SAVE: Save current progression as preset",
		"  - Enter name in dialog",
		"  - Stored per-scale-type for context",
		"  - Includes chords, beats, repeats, endpoint",
		"",
		"• LOAD: Load saved progression preset",
		"  - Left-click: Shows your saved presets",
		"  - Right-click: Opens Progression Templates menu",
		"  - Right-click preset name to delete",
		"  - Auto-restores all progression settings",
		"",
		"=== PROGRESSION TEMPLATES (NEW!) ===",
		"Right-click the LOAD button for 70+ preset progressions:",
		"",
		"• Pop / Rock: Axis of Awesome, 50s, Pachelbel, Andalusian",
		"• Jazz: ii-V-I, Turnaround, Autumn Leaves, Rhythm Changes",
		"• Blues: 12-Bar, Quick Change, 8-Bar, Minor Blues",
		"• Classical: Cadences, Circle of Fifths, Romanesca, La Folia",
		"• Modal: Dorian Vamp, Mixo Rock, Phrygian/Flamenco",
		"• Minor Keys: Aeolian, Epic Minor, Harmonic Minor",
		"• EDM: Trance Gate, House, Progressive, Future Bass",
		"• World/Folk: Celtic, Irish, Klezmer, Arabic",
		"",
		"Templates use scale degrees (I-VII) and auto-adapt to your",
		"current scale. A 'I-V-vi-IV' in C Major becomes C-G-Am-F,",
		"but in G Major becomes G-D-Em-C.",
		"",
		"Categories are filtered based on scale notes (e.g. Jazz",
		"templates require 7+ notes, so are hidden in Pentatonic).",
		"",
		"• INSERT: Convert progression to MIDI notes",
		"  - Inserts at edit cursor position",
		"  - Respects beats, repeats, and note length",
		"  - Creates MIDI item on selected track",
		"  - Use this to 'render' your progression",
		"",
		"=== WORKFLOW TIPS ===",
		"1. Build progression by Alt+clicking chord buttons",
		"2. Adjust timing with Ctrl+click (beats/repeats)",
		"3. Set loop endpoint for verse/chorus sections",
		"4. Use PLAY to audition your progression",
		"5. When satisfied, use INSERT to add to project",
		"6. SAVE progressions you want to reuse later",
		"",
		"=== PRESET MANAGEMENT ===",
		"Presets are saved per scale type:",
		"• C Major progressions saved separately from C Minor",
		"• Makes it easy to organize by key/mode",
		"• Presets stored in REAPER project settings",
		"",
	},
	
	-- Tab 6: Advanced
	{
		"ADVANCED FEATURES",
		"Keyboard Shortcuts & Technical Details",
		"",
		"=== MIDI TRIGGER MODE ===",
		"Trigger ChordGun chords using your MIDI keyboard.",
		"",
		"• Activation:",
		"  - Click the 'Trigger' button (Pin/Circle icon) to enable.",
		"  - Requires a MIDI input device enabled in REAPER.",
		"",
		"• Settings (Right-Click Trigger Button):",
		"  - Set Root Note: Change the starting note (Default: 24 / C1).",
		"  - Mapping Mode: Choose between Chromatic or Piano mapping.",
		"",
		"• Mapping Modes:",
		"  1. Chromatic (Default):",
		"     - 12 consecutive keys trigger chords 1-12.",
		"     - Example (Root C1): C1=Chord 1, C#1=Chord 2, D1=Chord 3...",
		"",
		"  2. Piano (White Keys):",
		"     - White keys trigger Scale Degrees 1-7 (I, ii, iii...)",
		"     - Black keys trigger Scale Degrees 8-12 (for extended scales)",
		"     - Example (Root C1): C1=Chord 1, D1=Chord 2, E1=Chord 3...",
		"",
		"=== LIVE PERFORMANCE FEATURES ===",
		"Turn ChordGun into an expressive instrument.",
		"",
		"• Velocity Sensitivity:",
		"  - Play trigger keys softly -> Soft chords.",
		"  - Play trigger keys hard -> Loud chords.",
		"  - Works automatically in MIDI Trigger Mode.",
		"",
		"• Live Inversion Control (Mod Wheel):",
		"  - Use your keyboard's Mod Wheel (CC1) to shift inversions live.",
		"  - Wheel Down: Lower inversions.",
		"  - Wheel Up: Higher inversions.",
		"  - Great for adding variation while playing chords.",
		"",
		"=== REMAP MODE (WHITE KEYS) ===",
		"Map the white keys of your keyboard to always play the correct scale notes.",
		"",
		"• Modes (Cycle via 'Filter' button):",
		"  1. Off: Normal MIDI behavior.",
		"  2. Filter: Blocks notes that are not in the selected scale.",
		"  3. Remap: Maps white keys (C, D, E...) to Scale Degrees (1, 2, 3...).",
		"     - Play C-Major on your keyboard -> Hear the selected scale.",
		"     - Great for jamming without hitting wrong notes.",
		"",
		"• Requirements:",
		"  - Requires 'TK_Scale_Filter.jsfx' on the track input FX.",
		"  - The script will prompt to install/add this automatically.",
		"",
		"• Channel 16 Bypass:",
		"  - When Remap is active, ChordGun previews chords on MIDI Channel 16.",
		"  - This bypasses the Remap logic so the preview sounds correct.",
		"  - This happens automatically; no user setup required.",
		"",
		"=== ARPEGGIATOR (ARP) ===",
		"Turn chords into rhythmic patterns.",
		"",
		"• Controls:",
		"  - ARP Button: Toggle On/Off.",
		"  - Pattern Menu: Up, Down, Up/Down, Random, Down/Up.",
		"  - Speed Menu: Sync (1/4, 1/8) or Time (ms).",
		"",
		"• Usage:",
		"  - Works with both 'Insert' (Shift+Click) and 'Play' (Click).",
		"  - Great for creating instant basslines or ostinatos.",
		"",
		"=== AUTOMATIC VOICE LEADING ===",
		"Smoothly connect chords by minimizing finger movement.",
		"",
		"• LEAD Button:",
		"  - When ON, the script automatically chooses the best inversion",
		"    for the NEXT chord based on the PREVIOUS chord.",
		"  - Example: C (Root) -> F (2nd Inv) instead of jumping up.",
		"",
		"=== MELODY GENERATOR ===",
		"Generate random melodies based on current scale/chord:",
		"• Click Melody button: Generate melody",
		"• Right-click Melody button: Open Settings Menu",
		"",
		"Melody Settings:",
		"• Rhythm Density: Slow, Normal, Fast",
		"• Octave Range: Low (C3-C4), Mid (C4-C5), High (C5-C6)",
		"• Note Selection: Chord Tones Only vs Include Scale Notes",
		"• Uses weighted probability to favor chord tones",
		"",
		"=== EXPORT OPTIONS ===",
		"Right-click the INSERT button for menu:",
		"1. Export to Chord Track (Text Items):",
		"   - Creates a dedicated track at top of project",
		"   - Inserts empty items with chord names",
		"   - Locks track height and items",
		"   - Great for visual guide while arranging",
		"",
		"2. Export to Project Regions:",
		"   - Creates REAPER Regions for each chord",
		"   - Regions named after chords",
		"   - Useful for navigating song structure",
		"",
		"=== KEYBOARD SHORTCUTS - SCALE NOTES ===",
		"Three rows for three octaves (10 keys per row):",
		"",
		"Preview (lowercase):",
		"• 1 2 3 4 5 6 7 8 9 0: Scale notes (octave +1)",
		"• q w e r t y u i o p: Scale notes (current octave)",
		"• a s d f g h j k l ;: Scale notes (octave -1)",
		"",
		"Insert (uppercase/shift):",
		"• ! @ # $ % ^ & * ( ): Insert notes (octave +1)",
		"• Q W E R T Y U I O P: Insert notes (current octave)",
		"• A S D F G H J K L :: Insert notes (octave -1)",
		"",
		"Adaptive System:",
		"• Works with all scale sizes (5-10 notes)",
		"• Diatonic: Uses first 7 keys",
		"• Messiaen 10-note: Uses all 10 keys per row",
		"• Unused keys inactive for current scale",
		"",
		"=== KEYBOARD SHORTCUTS - CHORDS ===",
		"Number row for chord buttons (10 keys):",
		"",
		"Preview:",
		"• 1 2 3 4 5 6 7 8 9 0: Preview chord I-x",
		"",
		"Insert:",
		"• ! @ # $ % ^ & * ( ): Insert chord I-x",
		"  (Shift + number keys)",
		"",
		"=== OTHER SHORTCUTS ===",
		"• SPACE / Middle Mouse: Stop all notes (same as KILL)",
		"• ESC: Close ChordGun window",
		"• Left/Right Arrow: Move edit cursor by grid",
		"• Alt + ,/.: Halve/double grid size",
		"• Ctrl + ,/.: Navigate tonic note",
		"• Ctrl + </>: Navigate scale type",
		"• Cmd/Ctrl + ,/.: Navigate inversions/chord types",
		"• Alt + ,/.: Change octave",
		"",
		"=== CIRCLE OF FIFTHS ===",
		"Interactive visualization window:",
		"",
		"Features:",
		"• Click any note to change tonic instantly",
		"• #/b button: Toggle sharp/flat notation",
		"• Fifths/Chromatic/Score/Guitar button: Toggle view mode",
		"• Shows all notes in current scale",
		"• Relative minor displayed below each major note",
		"• Auto-syncs with main window in real-time",
		"• Closes automatically when main window closes",
		"",
		"View Modes:",
		"1. Fifths View (Standard):",
		"   - Notes arranged by perfect fifths (C-G-D-A...)",
		"   - Best for functional harmony and key relationships",
		"   - Diatonic scales appear as contiguous blocks",
		"",
		"2. Chromatic View:",
		"   - Notes arranged chromatically (C-C#-D-D#...)",
		"   - Best for visualizing scale symmetry and geometry",
		"   - Shows 'Equivalent Tonics' with Gold Halos",
		"",
		"3. Score View (New in v2.2):",
		"   - Standard musical staff notation",
		"   - Shows notes of the selected scale on treble clef",
		"   - Great for sight-reading and theory reference",
		"",
		"4. Guitar View (New in v2.2):",
		"   - Fretboard visualization (Standard Tuning EADGBE)",
		"   - Shows scale notes across the neck",
		"   - Helps guitarists visualize scale patterns",
		"",
		"5. Linear View (New in v2.1.5):",
		"   - Piano-roll style interval visualization",
		"   - Shows scale structure linearly",
		"",
		"Equivalent Tonics (Gold Halos):",
		"• In Chromatic View, gold rings appear around notes",
		"• These notes share the EXACT same pitch set as current scale",
		"• Example: Diminished 7th scale repeats every minor 3rd",
		"• Visualizes 'Modes of Limited Transposition'",
		"",
		"Diatonic Scale Colors (harmonic distance):",
		"• Gold: Tonic (I)",
		"• Green: Dominant (+1 fifth, V)",
		"• Magenta: Subdominant (-1 fifth, IV)",
		"• Cyan: Supertonic (+2 fifths, ii)",
		"• Orange: Submediant (+3 fifths, vi)",
		"• Terracotta: Mediant (+4 fifths, iii)",
		"• Brown: Leading tone (tritone, vii°)",
		"",
		"Non-Diatonic Scale Colors:",
		"• Gold: Tonic/root note",
		"• Light blue: Other notes in scale",
		"• Gray: Notes outside scale",
		"",
		"Why different coloring?",
		"Harmonic distance is meaningful for diatonic scales",
		"(based on perfect fifth relationships), but less",
		"relevant for exotic, symmetrical, or non-tonal scales.",
		"",
		"=== PIANO KEYBOARD DISPLAY ===",
		"Visual feedback at bottom of window:",
		"",
		"Color coding:",
		"• Blue: Currently playing notes (live feedback)",
		"• Off-white: Notes in current scale",
		"• Gray: Notes outside scale",
		"• Note names labeled on white keys",
		"",
		"Remap Mode (when active):",
		"• Shows remap arrows on keys",
		"• Example in C Natural Minor:",
		"  'E→Eb' means white E key plays Eb",
		"• Helps visualize scale mapping",
		"",
		"=== WINDOW & UI ===",
		"• Scale button (1.0x/1.5x/2.0x):",
		"  Click to cycle UI scale for different monitor sizes",
		"  Settings persist across sessions",
		"",
		"• Theme Support:",
		"  - Automatically detects Light/Dark theme settings",
		"  - Optimized contrast for all views (Score, Guitar, etc.)",
		"",
		"• DOCK/UNDOCK button:",
		"  Toggle docker integration",
		"  Docked mode saves screen space",
		"",
		"• Window width adapts automatically:",
		"  Narrow for pentatonic (5 notes)",
		"  Wide for Messiaen Mode 7 (10 notes)",
		"  Maintains proper button spacing",
		"",
		"=== TECHNICAL NOTES ===",
		"• All settings saved in REAPER ExtState",
		"• Presets stored per-project",
		"• Compatible with Windows, macOS, Linux",
		"• Requires REAPER v5.0 or later",
		"• TK Scale Filter JSFX included for live filtering",
		"",
	},
	
	-- Tab 7: About
	{
		"ABOUT CHORDGUN (TK MOD)",
		"",
		"VERSION: 2.5.1",
		"RELEASE: December 2025",
		"",
		"=== CREDITS ===",
		"",
		"Original ChordGun:",
		"• Created by: pandabot",
		"• Concept: Chord generation with scale awareness",
		"",
		"TK Modifications by: TouristKiller",
		"• Absolute chord storage for progressions (v2.5.1)",
		"• Chord Style filter system (v2.5.0)",
		"• MIDI Trigger system with custom mapping",
		"• Scale filter/remap system with JSFX integration",
		"• Real-time chord recognition engine",
		"• Circle of Fifths visualization (5 Views)",
		"• Expanded scale library (8 → 88 scales)",
		"• Two-level scale organization system",
		"• Educational tooltips with music theory",
		"• World music, jazz, blues, and metal scale systems",
		"• All 32 Messiaen modes with transpositions",
		"• Enhanced UI with adaptive window sizing",
		"• Chord progression builder with templates",
		"• Arpeggiator and Melody Generator",
		"",
		"=== VERSION 2.5.1 HIGHLIGHTS ===",
		"",
		"Progression Improvements:",
		"• Absolute Chord Storage:",
		"  - Progressions now store root note + chord type",
		"  - Changing scale/filter no longer changes playback",
		"  - Backwards compatible with old preset files",
		"",
		"• Visual Feedback:",
		"  - Correct chord button highlights during playback",
		"  - Out-of-scale chords show correct color in display",
		"  - Extended chord names (Amaj#11) display correctly",
		"  - Orange overlay when chord not visible in filter",
		"  - Piano keys clear properly when releasing buttons",
		"",
		"=== VERSION 2.5.0 HIGHLIGHTS ===",
		"",
		"UI Reorganization:",
		"• Lead button moved to bottom row (between Drop and Melody)",
		"• Circle of Fifths accessible via icon in chord display",
		"• Track name shown in chord display area",
		"",
		"Chord Style System:",
		"• Combined filter dropdown with style presets:",
		"  - Simple, Standard, Extended, Ambient, Jazz, Pop, Neo-Soul",
		"• 'All' checkbox to show out-of-scale chords",
		"",
		"=== VERSION 2.4.x HIGHLIGHTS ===",
		"",
		"MIDI Trigger Improvements:",
		"• Cascade Fix: Chord notes no longer re-trigger",
		"• Virtual MIDI Detection: Cross-platform support",
		"• Channel 16 Bypass: Proper JSFX handling",
		"• Custom Mapping: Assign any MIDI note to any chord",
		"• Column Mode: Single keys trigger scale degrees",
		"• Preset System: Save/Load trigger mappings",
		"• Piano Trigger Visualization: Separate trigger colors",
		"",
		"=== VERSION 2.3.x HIGHLIGHTS ===",
		"",
		"• Progression Templates: 70+ preset progressions",
		"• Genre categories: Pop/Rock, Jazz, Blues, Classical, Modal",
		"• Harmonic Compass: Smart next-chord suggestions",
		"• Extended Chord Vocabulary: 9th, 11th, 13th, 6/9, etc.",
		"• Right-Click Context Menu: ii-V-I, Tritone Subs",
		"• 6 Color Themes: Dark, Light, Color, Neon, Ocean, Mono",
		"",
		"=== VERSION 2.2.x HIGHLIGHTS ===",
		"",
		"• MIDI Trigger Mode: Trigger chords via MIDI keyboard",
		"• Remap Mode: Map white keys to scale notes",
		"• Surprise Me: Dice button for random progressions",
		"• Sync Play: Sync with Reaper transport",
		"• Per-slot Inversion/Octave: Alt+Click to save",
		"• Automatic Voice Leading (Lead button)",
		"• Arpeggiator with multiple patterns",
		"• Score View and Guitar View",
		"",
		"=== EARLIER VERSIONS ===",
		"",
		"v2.1.x: Chromatic View, Melody Generator, Power Chord Recognition",
		"v2.0.x: 88 scales, World Music, Jazz, Blues, Messiaen modes",
		"",
		"=== GETTING HELP ===",
		"",
		"Enable Tooltips:",
		"Check the tooltip box (☑) next to LOAD button",
		"Hover over any control for detailed help",
		"",
		"Online Resources:",
		"• GitHub: TouristKiller/TK-Scripts",
		"• REAPER Forum: Search 'ChordGun TK'",
		"",
		"=== LICENSE ===",
		"Based on original ChordGun by pandabot",
		"Modified and extended by TouristKiller",
		"",
		"Free to use and modify",
		"No warranty provided",
		"Use at your own risk",
		"",
		"=== FEEDBACK ===",
		"Found a bug? Have a feature request?",
		"• Post in REAPER Forums",
		"• Create GitHub issue",
		"• Tag: ChordGun TK Mod",
		"",
		"Enjoy making music!",
		"- TouristKiller",
	}
}

local helpLines = helpContent[activeTab]

local baseWindowWidth = 800
local baseWindowHeight = 650
local lineHeight = 24
local fontSize = 18
local mouseWasDown = false

-- Get saved window position
local savedX = tonumber(reaper.GetExtState("TK_ChordGun_Help", "windowX")) or -1
local savedY = tonumber(reaper.GetExtState("TK_ChordGun_Help", "windowY")) or -1
local uiScale = tonumber(reaper.GetExtState("TK_ChordGun_Help", "uiScale")) or 1.0

local windowWidth = math.floor(baseWindowWidth * uiScale)
local windowHeight = math.floor(baseWindowHeight * uiScale)

-- Initialize window with saved position
gfx.init("ChordGun Help", windowWidth, windowHeight, 0, savedX, savedY)

-- Function to calculate max scroll for current tab
function getMaxScroll()
	return math.max(0, (#helpLines * lineHeight) - (windowHeight - tabHeight) + 40)
end

-- Function to draw tabs
function drawTabs()
	local tabWidth = windowWidth / #tabs
	local tabFontSize = math.max(14, math.floor(windowWidth / 50))  -- Scale with window width
	
	for i, tabName in ipairs(tabs) do
		local x = (i - 1) * tabWidth
		local y = 0
		
		-- Tab background
		if i == activeTab then
			gfx.set(0.25, 0.25, 0.25, 1)  -- Active tab darker
		else
			gfx.set(0.18, 0.18, 0.18, 1)  -- Inactive tab lighter
		end
		gfx.rect(x, y, tabWidth, tabHeight, 1)
		
		-- Tab border
		gfx.set(0.4, 0.4, 0.4, 1)
		gfx.rect(x, y, tabWidth, tabHeight, 0)
		
		-- Tab text
		if i == activeTab then
			gfx.set(1.0, 0.84, 0.0, 1)  -- Gold for active
		else
			gfx.set(0.7, 0.7, 0.7, 1)  -- Gray for inactive
		end
		gfx.setfont(2, "Arial", tabFontSize, string.byte('b'))
		local textW, textH = gfx.measurestr(tabName)
		gfx.x = x + (tabWidth - textW) / 2
		gfx.y = y + (tabHeight - textH) / 2
		gfx.drawstr(tabName)
	end
	
	-- Bottom border of tab bar
	gfx.set(0.5, 0.5, 0.5, 1)
	gfx.rect(0, tabHeight, windowWidth, 1, 1)
end

-- Function to handle tab clicks
function handleTabClick(mx, my)
	if my <= tabHeight then
		local tabWidth = windowWidth / #tabs
		local clickedTab = math.floor(mx / tabWidth) + 1
		if clickedTab >= 1 and clickedTab <= #tabs and clickedTab ~= activeTab then
			activeTab = clickedTab
			helpLines = helpContent[activeTab]
			scrollOffset = 0  -- Reset scroll when changing tabs
			return true
		end
	end
	return false
end

function main()
	-- Check if window was resized
	local newWidth = gfx.w
	local newHeight = gfx.h
	
	if newWidth ~= windowWidth or newHeight ~= windowHeight then
		windowWidth = newWidth
		windowHeight = newHeight
		fontSize = math.max(14, math.floor(windowHeight / 32))
		gfx.setfont(1, "Arial", fontSize)
		lineHeight = math.floor(fontSize * 1.3)
	end
	
	maxScroll = getMaxScroll()
	
	-- Handle mouse clicks for tabs
	local mouseDown = gfx.mouse_cap & 1 == 1
	if mouseDown and not mouseWasDown then
		handleTabClick(gfx.mouse_x, gfx.mouse_y)
	end
	mouseWasDown = mouseDown
	
	-- Handle mouse wheel for scrolling
	local mouseWheel = gfx.mouse_wheel
	if mouseWheel ~= 0 then
		scrollOffset = scrollOffset - (mouseWheel * 8)  -- Reduced to 8 for very smooth scrolling
		scrollOffset = math.max(0, math.min(scrollOffset, maxScroll))
		gfx.mouse_wheel = 0
	end
	
	-- Clear background
	gfx.set(0.15, 0.15, 0.15, 1)
	gfx.rect(0, 0, windowWidth, windowHeight, 1)
	
	-- Draw help text (below tabs)
	gfx.set(0.9, 0.9, 0.9, 1)
	gfx.setfont(1, "Arial", fontSize)
	
	local padding = math.floor(windowWidth * 0.025)
	local yPos = tabHeight + padding - scrollOffset
	for i, line in ipairs(helpLines) do
		if yPos > tabHeight - lineHeight and yPos < windowHeight then
			gfx.x = padding
			gfx.y = yPos
			gfx.drawstr(line)
		end
		yPos = yPos + lineHeight
	end
	
	-- Draw tabs (on top of text)
	drawTabs()
	
	-- Draw scrollbar if needed
	if maxScroll > 0 then
		local scrollbarWidth = math.max(10, math.floor(windowWidth * 0.02))
		local scrollbarPadding = math.floor(windowHeight * 0.025)
		local scrollbarHeight = windowHeight - tabHeight - (scrollbarPadding * 2)
		local contentHeight = #helpLines * lineHeight
		local thumbHeight = math.max(40, scrollbarHeight * ((windowHeight - tabHeight) / contentHeight))
		local thumbPos = tabHeight + scrollbarPadding + (scrollOffset / maxScroll) * (scrollbarHeight - thumbHeight)
		
		-- Scrollbar background
		gfx.set(0.25, 0.25, 0.25, 1)
		gfx.rect(windowWidth - scrollbarWidth - scrollbarPadding, tabHeight + scrollbarPadding, scrollbarWidth, scrollbarHeight, 1)
		
		-- Scrollbar thumb
		gfx.set(0.5, 0.5, 0.5, 1)
		gfx.rect(windowWidth - scrollbarWidth - scrollbarPadding, thumbPos, scrollbarWidth, thumbHeight, 1)
	end
	
	gfx.update()
	
	local char = gfx.getchar()
	if char == 27 or char == -1 then  -- ESC or window closed
		return
	end
	
	reaper.SetExtState("TK_ChordGun_Help", "heartbeat", tostring(reaper.time_precise()), false)
	reaper.defer(main)
end

main()
